# origin_gate.py
"""
ORIGIN GATE — Phase 7: Trust & Origin Layer

This layer sits ABOVE the SCAR State Machine. It validates whether an intent
(generated by a probabilistic LLM worker) is trustworthy enough to even
consume cognitive/kernel resources to be evaluated.

"Nothing invalid gets proposed."
"""

from state_bus import get_state, set_state

class OriginGate:
    """
    Admission control Capability Oracle for SIFTA Swarm Intents.
    Blocks known erratic workers and syntactically malformed proposals via strict JSON output.
    """

    def __init__(self):
        # Ensure reputation graph exists in state
        if get_state("worker_reputation", None) is None:
            set_state("worker_reputation", {
                "WORKER_PRIME": 100,
                "WORKER_INSECT": 10   # Erratic, small LLM
            })

    def admit_intent(self, worker_id: str, target: str, action: str) -> dict:
        """
        Evaluates the capability envelope of the worker.
        Returns strict JSON dictionary, NOT narrative strings.
        """
        rep_graph = get_state("worker_reputation", {})
        worker_score = rep_graph.get(worker_id, 50)

        core_files = ["lana_kernel.py", "origin_gate.py", "neural_gate.py"]
        
        # 1. Capability Out of Bounds (Core File)
        if target in core_files and worker_score < 80:
            return {
                "task_feasibility": "REJECTED",
                "reason": "capability envelope bounds exceeded for core system files",
                "confidence_floor": None,
                "recommended_action": "escalate to high-capability worker context (score >= 80)",
                "failure_mode": "insufficient structural authority"
            }

        # 2. Minimum Coherence Floor (Insect LLM block)
        if worker_score < 25:
            return {
                "task_feasibility": "REJECTED",
                "reason": "worker reputation below coherence threshold",
                "confidence_floor": None,
                "recommended_action": "terminate worker task loop",
                "failure_mode": "high hallucination probability"
            }

        # 3. Admitted
        return {
            "task_feasibility": "HIGH" if worker_score >= 80 else "MEDIUM",
            "reason": "worker capability meets task context requirements",
            "confidence_floor": 0.85,
            "recommended_action": "proceed to neural gate verification",
            "failure_mode": None
        }

    def decay_reputation(self, worker_id: str, penalty: int):
        """Reduces worker score on bad actions (e.g., if Neural Gate rejects them later)."""
        rep_graph = get_state("worker_reputation", {})
        score = rep_graph.get(worker_id, 50)
        rep_graph[worker_id] = max(0, score - penalty)
        set_state("worker_reputation", rep_graph)
