# origin_gate.py
"""
ORIGIN GATE — Phase 7: Trust & Origin Layer

This layer sits ABOVE the SCAR State Machine. It validates whether an intent
(generated by a probabilistic LLM worker) is trustworthy enough to even
consume cognitive/kernel resources to be evaluated.

"Nothing invalid gets proposed."
"""

from state_bus import get_state, set_state

class OriginGate:
    """
    Admission control for SIFTA Swarm Intents.
    Blocks known erratic workers and syntactically malformed proposals.
    """

    def __init__(self):
        # Ensure reputation graph exists in state
        if get_state("worker_reputation", None) is None:
            set_state("worker_reputation", {
                "WORKER_PRIME": 100,
                "WORKER_INSECT": 10   # Erratic, small LLM
            })

    def admit_intent(self, worker_id: str, target: str, action: str) -> tuple[bool, str]:
        """
        Evaluates the origin of the intent.
        Returns (is_admitted, reason).
        """
        rep_graph = get_state("worker_reputation", {})
        worker_score = rep_graph.get(worker_id, 50) # default new worker score

        # 1. Reputation Hard Gate
        # Core system files require a high trust score to even propose a change.
        core_files = ["lana_kernel.py", "origin_gate.py", "neural_gate.py"]
        
        if target in core_files and worker_score < 80:
            return False, f"[🔰 ORIGIN REJECTED] Worker {worker_id} (Rep: {worker_score}) lacks authority to mutate core files."

        # 2. Minimum Coherence Floor
        # Insect LLMs get blocked from any structural execution if they drop below a threshold
        if worker_score < 25:
            return False, f"[🔰 ORIGIN REJECTED] Worker {worker_id} (Rep: {worker_score}) is below minimum coherence threshold. Intent annihilated."

        return True, "[🔰 ORIGIN ADMITTED] Worker trusted. Intent proceeding to SCAR queue."

    def decay_reputation(self, worker_id: str, penalty: int):
        """Reduces worker score on bad actions (e.g., if Neural Gate rejects them later)."""
        rep_graph = get_state("worker_reputation", {})
        score = rep_graph.get(worker_id, 50)
        rep_graph[worker_id] = max(0, score - penalty)
        set_state("worker_reputation", rep_graph)
