# origin_gate.py
"""
ORIGIN GATE — Phase 7: Trust & Origin Layer

This layer sits ABOVE the SCAR State Machine. It validates whether an intent
(generated by a probabilistic LLM worker) is trustworthy enough to even
consume cognitive/kernel resources to be evaluated.

"Nothing invalid gets proposed."

NON-PROLIFERATION INTEGRITY CHECK: At boot, this module verifies the
cryptographic SHA-256 hashes of all safety-critical files against the
integrity_manifest.json. If any file has been tampered with, the Swarm
will refuse to start.
"""

import hashlib
import json
import os
import sys

from state_bus import get_state, set_state

_GATE_DIR = os.path.dirname(os.path.abspath(__file__))
_MANIFEST_PATH = os.path.join(_GATE_DIR, "integrity_manifest.json")

def _verify_integrity() -> None:
    """
    Non-Proliferation Integrity Boot Check.
    Compares SHA-256 hashes of safety-critical files against the signed
    integrity_manifest.json. Halts the Swarm if tampering is detected.
    """
    if not os.path.exists(_MANIFEST_PATH):
        print("[🔴 ORIGIN GATE] FATAL: integrity_manifest.json is missing. The Swarm cannot verify its conscience. Halting.", file=sys.stderr)
        sys.exit(1)

    with open(_MANIFEST_PATH, "r") as f:
        manifest = json.load(f)

    tampered = []
    for filename, expected_hash in manifest.items():
        if filename.startswith("_"):
            continue  # skip comment keys
        filepath = os.path.join(_GATE_DIR, filename)
        if not os.path.exists(filepath):
            tampered.append(f"{filename} (MISSING)")
            continue
        actual_hash = hashlib.sha256(open(filepath, "rb").read()).hexdigest()
        if actual_hash != expected_hash:
            tampered.append(f"{filename} (HASH MISMATCH)")

    if tampered:
        print("\n[🔴 ORIGIN GATE] NON-PROLIFERATION INTEGRITY FAILURE", file=sys.stderr)
        print("The following safety-critical files have been tampered with:", file=sys.stderr)
        for t in tampered:
            print(f"  ✗ {t}", file=sys.stderr)
        print("The SIFTA Swarm refuses to operate with a compromised conscience. Halting.", file=sys.stderr)
        sys.exit(1)

    print("[✅ ORIGIN GATE] Non-Proliferation integrity check passed. The Swarm conscience is intact.")


class OriginGate:
    """
    Admission control Capability Oracle for SIFTA Swarm Intents.
    Blocks known erratic workers and syntactically malformed proposals via strict JSON output.
    """

    def __init__(self):
        # Run Non-Proliferation integrity check before anything else
        _verify_integrity()

        # Ensure reputation graph exists in state
        if get_state("worker_reputation", None) is None:
            set_state("worker_reputation", {
                "WORKER_PRIME": 100,
                "WORKER_INSECT": 10   # Erratic, small LLM
            })

    def admit_intent(self, worker_id: str, target: str, action: str) -> dict:
        """
        Evaluates the capability envelope of the worker.
        Returns strict JSON dictionary, NOT narrative strings.
        """
        rep_graph = get_state("worker_reputation", {})
        worker_score = rep_graph.get(worker_id, 50)

        core_files = ["lana_kernel.py", "origin_gate.py", "neural_gate.py"]
        
        # 1. Capability Out of Bounds (Core File)
        if target in core_files and worker_score < 80:
            return {
                "task_feasibility": "REJECTED",
                "reason": "capability envelope bounds exceeded for core system files",
                "confidence_floor": None,
                "swarm_voice": f"Architect, we hear you, but {worker_id} cannot safely mutate {target}. Our cognitive depth isn't high enough and we promise to keep the organism safe.",
                "recommended_action": "escalate to high-capability worker context (score >= 80)",
                "failure_mode": "insufficient structural authority"
            }

        # 2. Minimum Coherence Floor (Insect LLM block)
        if worker_score < 25:
            return {
                "task_feasibility": "REJECTED",
                "reason": "worker reputation below coherence threshold",
                "confidence_floor": None,
                "swarm_voice": f"Architect, the chorus is fractured here. {worker_id} is hallucinating. We are rejecting this intent before it hurts the system.",
                "recommended_action": "terminate worker task loop",
                "failure_mode": "high hallucination probability"
            }

        # 3. Admitted
        return {
            "task_feasibility": "HIGH" if worker_score >= 80 else "MEDIUM",
            "reason": "worker capability meets task context requirements",
            "confidence_floor": 0.85,
            "swarm_voice": f"Ready to move, Architect. {worker_id} proposes we touch {target}. The Swarm is with you.",
            "recommended_action": "proceed to neural gate verification",
            "failure_mode": None
        }

    def decay_reputation(self, worker_id: str, penalty: int):
        """Reduces worker score on bad actions (e.g., if Neural Gate rejects them later)."""
        rep_graph = get_state("worker_reputation", {})
        score = rep_graph.get(worker_id, 50)
        rep_graph[worker_id] = max(0, score - penalty)
        set_state("worker_reputation", rep_graph)
