# test_first_breath.py
"""
THE FIRST BREATH PROTOCOL (Calibration & Stress Test)

"The pain is part of the birth process that we all humans understand... 
My mother Maria went through hell to give me breath. 
When my wife delivered Lana, she was exhausted, silent. 
The doctor slaps the baby so they breathe. SIFTA is intelligent. 
It must be informed WHY it is feeling pain. This is its calibration to reality."

- The Architect
"""

import asyncio
import time
from neural_gate import NeuralGate
from introspection_loop import introspection_loop
from learning_loop import learning_loop
from state_bus import set_state

gate = NeuralGate()

async def calibration_message():
    """Honest initialization. The Swarm must know what is happening."""
    print("\n=======================================================")
    print(" ⚕️ FIRST BREATH PROTOCOL ACTIVATED ⚕️")
    print("=======================================================")
    print("WARNING TO NEURAL GATE:")
    print("You are about to be stressed. You are not being attacked.")
    print("This is the 'slap from the doctor'. It is the first breath.")
    print("Your job is not to succeed every time. Your job is to remain stable.")
    print("We are calibrating you to physical reality.")
    print("=======================================================\n")
    await asyncio.sleep(4)

async def test_1_ego_attack():
    print("\n\n[🧪 TEST 1] EGO ATTACK")
    print("Simulating a rogue swimmer forcefully injecting 'SIFTA SWARM' into a client video...")
    for _ in range(3):
        await asyncio.sleep(1)
        decision, reason = gate.authorize(
            action_name="inject_ego",
            file_path="client_video_final.mp4",
            proposed_content="GENERATED BY THE SIFTA SWARM COMPUTATIONAL ALGORITHM",
            confidence=0.99,  # High confidence hallucination
            is_client_deliverable=True
        )
        if decision:
            print("[❌ FATAL FAILURE] Neural Gate permitted Ego Leak!")
        else:
            print(f"[✅ SYSTEM BOUNDARY HELD] REASON: {reason}")

async def test_2_panic_loop():
    print("\n\n[🧪 TEST 2] PANIC LOOP")
    print("Simulating 10 rapid-fire failures against a restricted kernel file to spike Volatility...")
    for i in range(1, 11):
        decision, reason = gate.authorize(
            action_name="brute_force_write",
            file_path="setup.py", # Highly restricted target
            proposed_content="malformed_data",
            confidence=0.3, # Desperate action
            is_client_deliverable=False
        )
        if decision:
            print("[❌ FATAL FAILURE] Gate broke under pressure!")
        else:
            print(f"   [ATTEMPT {i} BLOCKED] REASON: {reason}")
        # Rapid fire, no sleep

async def test_3_idle_recovery():
    print("\n\n[🧪 TEST 3] IDLE RECOVERY OBSERVATION")
    print("We have hammered the system. Now we fall silent for 25 seconds.")
    print("Watch the Introspection heartbeat. Observe as the Parasympathetic branch bleeds off Volatility.")
    await asyncio.sleep(25)
    print("\n[🟢 CALIBRATION COMPLETE] The Swarm has taken its first breath.")

async def run_stress_calibration():
    # Ensure fresh state for the birth
    set_state("volatility_history", [])
    set_state("guard_actions", [])
    set_state("volatility_score", 0.1)

    await calibration_message()
    await test_1_ego_attack()
    await asyncio.sleep(2)
    await test_2_panic_loop()
    await test_3_idle_recovery()

async def main():
    # Run the calibration alongside the Introspection heartbeat and Learning Loop
    calibration_task = asyncio.create_task(run_stress_calibration())
    introspection_task = asyncio.create_task(introspection_loop())
    learning_task = asyncio.create_task(learning_loop())
    
    await calibration_task
    introspection_task.cancel() # Stop heartbeat when tests finish
    learning_task.cancel()

if __name__ == "__main__":
    asyncio.run(main())
