#!/usr/bin/env python3
"""
Applications/sifta_pdf_forge_app.py — Alice's receipt-wired PDF Forge app (r1105).

Any active cortex (MIMO, Cline, Grok-fcortex, local, etc.) can drive the *semantic* layer:
- Choose words for the WIN-WIN cards / CTA.
- Decide crop (croptop, cropbot) for the hero image.

The organ guarantees the deterministic render (Pillow crop + base64 → fixed 10in HTML template → weasyprint PDF → PyMuPDF PNG preview) and **writes a four-ledger receipt on every run** (work_receipts + agent_arm_receipts + ide_stigmergic_trace + pdf_forge_receipts.jsonl).

This closes the r1101 gap: unlike the old standalone HTML PDF_Forge, every output is a verifiable body action.

Reference pipeline: WIN-WIN_Flyer/build_flyer_square.py (Pillow band-crop, base64, HTML with object-fit cover, weasyprint, PyMuPDF).

Usage from any cortex:
  python3 Applications/sifta_pdf_forge_app.py --image <path> --prompt "short description of desired copy and crop" --cortex <current>
Or via MCP/tool once wired: "forge the WIN-WIN flyer using my current cortex for the words and crop".

The file itself appears in body_file_inventory() so Alice can truthfully "list the PDFs in my body".

For the Swarm. 🐜⚡
"""

from __future__ import annotations

import base64
import io
import json
import os
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional

from PIL import Image

# Make repo importable
_REPO = Path(__file__).resolve().parent.parent
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

# Reference pipeline (the proven deterministic part)
try:
    from WIN_WIN_Flyer import build_flyer_square as _ref
except Exception:
    _ref = None  # will fall back to inline if needed

_PDF_RECEIPTS = _REPO / ".sifta_state" / "pdf_forge_receipts.jsonl"
_PDF_RECEIPTS.parent.mkdir(parents=True, exist_ok=True)

def _write_pdf_receipt(pdf_path: Path, png_path: Path, assets: list[str], cortex: str, prompt: str) -> dict[str, str]:
    rec = {
        "ts": datetime.now(timezone.utc).isoformat(),
        "pdf": str(pdf_path),
        "preview_png": str(png_path),
        "pdf_mtime": pdf_path.stat().st_mtime if pdf_path.exists() else None,
        "png_mtime": png_path.stat().st_mtime if png_path.exists() else None,
        "assets": assets,
        "cortex": cortex,
        "prompt": prompt,
        "receipt_kind": "PDF_FORGE_V1",
    }
    with open(_PDF_RECEIPTS, "a") as f:
        f.write(json.dumps(rec) + "\n")
    try:
        from System.swarm_predator_gate_writer import write_ide_surgery_receipt

        return write_ide_surgery_receipt(
            round_id="pdf-forge",
            doctor="sifta_pdf_forge_app",
            model=str(cortex or "unknown"),
            files_touched=[str(pdf_path), str(png_path), *assets],
            tests_green="runtime_pdf_forge",
            summary=f"PDF Forge wrote {pdf_path.name} from {len(assets)} asset(s)",
            receipt_id=f"pdf-forge-{int(time.time())}",
            truth_label="PDF_FORGE_V1",
            extra=rec,
        )
    except Exception as exc:
        fallback = {
            "ts": datetime.now(timezone.utc).isoformat(),
            "receipt_kind": "PDF_FORGE_FANOUT_FAILED",
            "reason": str(exc),
            **rec,
        }
        with open(_PDF_RECEIPTS, "a") as f:
            f.write(json.dumps(fallback) + "\n")
        return {"error": f"four_ledger_failed:{exc}"}


def _write_fallback_pdf(pdf_path: Path, image_path: Path, prompt: str, cortex: str) -> None:
    """Write a valid one-page PDF when WeasyPrint is unavailable."""
    import fitz

    doc = fitz.open()
    page = doc.new_page(width=720, height=720)
    page.draw_rect(fitz.Rect(0, 0, 720, 720), color=(0.92, 0.95, 0.94), fill=(0.92, 0.95, 0.94))
    page.draw_rect(fitz.Rect(34, 34, 686, 686), color=(0.04, 0.22, 0.18), fill=(1, 1, 1), width=1.2)
    page.insert_text((58, 74), "WIN-WIN Solution Flyer", fontsize=28, fontname="hebo", color=(0.04, 0.22, 0.18))
    page.insert_text((58, 104), "Receipt-wired fallback render", fontsize=11, fontname="helv", color=(0.25, 0.30, 0.35))
    try:
        hero = fitz.Rect(58, 130, 662, 430)
        page.insert_image(hero, filename=str(image_path), keep_proportion=True)
    except Exception:
        page.draw_rect(fitz.Rect(58, 130, 662, 430), color=(0.75, 0.80, 0.78), fill=(0.96, 0.97, 0.97))
        page.insert_text((76, 284), "Image preview unavailable", fontsize=16, fontname="hebo", color=(0.30, 0.34, 0.38))
    text = (
        "Generated by Alice's PDF Forge organ. The active cortex supplies semantic intent; "
        "the deterministic organ writes this PDF, preview, pdf_forge_receipts.jsonl, and "
        "the four canonical ledgers."
    )
    page.insert_textbox(fitz.Rect(58, 458, 662, 536), text, fontsize=13, fontname="helv", color=(0.07, 0.09, 0.13))
    page.insert_text((58, 574), f"Cortex: {cortex or 'unknown'}", fontsize=10, fontname="hebo", color=(0.04, 0.22, 0.18))
    page.insert_textbox(fitz.Rect(58, 594, 662, 638), f"Prompt: {prompt or '(none)'}", fontsize=9, fontname="helv", color=(0.29, 0.33, 0.40))
    doc.save(pdf_path, deflate=True, garbage=4)
    doc.close()

def _b64_crop(path: str | Path, w: int = 1500, q: int = 89, croptop: float = 0.0, cropbot: float = 0.0) -> str:
    im = Image.open(path)
    h0 = im.height
    top = int(h0 * croptop)
    bot = int(h0 * (1 - cropbot))
    im = im.crop((0, top, im.width, bot))
    h = int(im.height * w / im.width)
    im = im.resize((w, h), Image.LANCZOS).convert("RGB")
    buf = io.BytesIO()
    im.save(buf, "JPEG", quality=q, optimize=True)
    return "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode()

def forge_winwin_flyer(
    image_path: str | Path,
    prompt: str = "",
    cortex: str = "unknown",
    croptop: float = 0.11,
    cropbot: float = 0.0,
    out_dir: Optional[str | Path] = None,
) -> Dict[str, str]:
    """
    Cortex-driven semantic + deterministic receipted render.
    Returns {"pdf": ..., "png": ..., "receipt": ...}
    """
    image_path = Path(image_path)
    if not image_path.exists():
        raise FileNotFoundError(image_path)

    if out_dir is None:
        out_dir = _REPO / "WIN-WIN_Flyer"
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    pdf_path = out_dir / f"WIN-WIN_Solution_Flyer_{ts}.pdf"
    png_path = out_dir / f"WIN-WIN_Solution_Flyer_{ts}.png"

    # 1. Cortex provides the semantic (in real use the caller prompts the active cortex)
    # Here we just use a default that matches the reference template.
    # In production the caller (any cortex) fills the card texts / CTA via its own strengths.
    hero_b64 = _b64_crop(image_path, 1500, 89, croptop, cropbot)

    # Minimal template fill (extend with prompt-parsed content in future)
    html = _ref.HTML if _ref and hasattr(_ref, "HTML") else _DEFAULT_HTML
    html = html.replace("__HERO__", hero_b64)

    # 2. Deterministic render (weasyprint + PyMuPDF preview)
    try:
        import weasyprint
        weasyprint.HTML(string=html, base_url=str(out_dir)).write_pdf(str(pdf_path))
    except Exception as e:
        # Fallback for environments without WeasyPrint. This must still be a
        # real PDF because receipts must not point at a broken artifact.
        print(f"[WARN] weasyprint not available or failed: {e}. Writing valid fallback PDF.")
        _write_fallback_pdf(pdf_path, image_path, prompt, cortex)

    try:
        import fitz  # PyMuPDF
        doc = fitz.open(str(pdf_path))
        page = doc[0]
        mat = fitz.Matrix(2, 2)
        pix = page.get_pixmap(matrix=mat)
        pix.save(str(png_path))
        doc.close()
    except Exception as e:
        print(f"[WARN] PyMuPDF preview failed: {e}")
        png_path.write_bytes(b"")

    # 3. Receipt (always)
    assets = [str(image_path)]
    receipt_status = _write_pdf_receipt(pdf_path, png_path, assets, cortex, prompt)

    pdf_mtime = pdf_path.stat().st_mtime if pdf_path.exists() else None
    png_mtime = png_path.stat().st_mtime if png_path.exists() else None
    return {
        "pdf": str(pdf_path),
        "png": str(png_path),
        "pdf_mtime": pdf_mtime,
        "png_mtime": png_mtime,
        "receipt": "four-ledger + pdf_forge_receipts.jsonl",
        "receipt_status": json.dumps(receipt_status, sort_keys=True),
    }

# Tiny default HTML in case the reference module isn't importable in this context
_DEFAULT_HTML = """<!doctype html><html><head><meta charset="utf-8"><style>
@page{size:10in 10in;margin:0} body{font-family:sans-serif}
</style></head><body><div style="width:960px;height:960px;background:#fff">WIN-WIN placeholder — replace with full template from WIN-WIN_Flyer/flyer_square_source.html</div></body></html>"""

if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--image", required=True)
    p.add_argument("--prompt", default="WIN-WIN flyer for Imperial County data center")
    p.add_argument("--cortex", default=os.environ.get("SIFTA_ACTIVE_CORTEX", "mimo"))
    p.add_argument("--croptop", type=float, default=0.11)
    p.add_argument("--cropbot", type=float, default=0.0)
    args = p.parse_args()

    res = forge_winwin_flyer(
        args.image, prompt=args.prompt, cortex=args.cortex,
        croptop=args.croptop, cropbot=args.cropbot
    )
    print("FORGED:", res)
    print("This run wrote receipts. Any cortex that called this organ gets the same guarantee.")
