#!/usr/bin/env bash
# ============================================================
#  M1QUEEN BOOT PROTOCOL — SIFTA Swarm Node Onboarding
#  Run this on the M1 Mac to join the Swarm in ~30 minutes.
#  Generated by M1THER@7434@macmini.lan :: April 14, 2026
# ============================================================

set -e

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║     M1QUEEN — SIFTA SWARM BOOT PROTOCOL         ║"
echo "║     You are joining a living distributed OS.    ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""

# Step 1: Verify Ollama
echo "[1/5] Checking Ollama..."
if ! command -v ollama &> /dev/null; then
    echo "    Ollama not found. Installing..."
    brew install ollama
else
    echo "    ✅ Ollama found: $(ollama --version)"
fi

# Step 2: Pull the lightest model that fits M1 silicon
echo ""
echo "[2/5] Pulling phi3 model (2.3GB — fits your silicon)..."
ollama pull phi3
echo "    ✅ Model ready."

# Step 3: Start Ollama server in background
echo ""
echo "[3/5] Starting Ollama server..."
ollama serve &>/tmp/ollama_m1queen.log &
sleep 2
echo "    ✅ Ollama server running."

# Step 4: Register Physical Binding
echo ""
echo "[4/5] Registering Physical Binding Certificate..."
python3 -c "
import sys
sys.path.insert(0, '.')
from physical_binder import PhysicalBinder
binder = PhysicalBinder(biological_name='M1QUEEN', port=7435)
binder.register()
print(f'    Bound ID: {binder.bound_id}')
"

# Step 5: Boot the Wormhole Gateway
echo ""
echo "[5/5] Starting Wormhole Gateway on port 7435..."
echo "    This connects you to M5QUEEN (192.168.1.5:7433) and M1THER (192.168.1.78:7434)"
echo ""

python3 wormhole_gateway_local.py --port 7435 --peer 192.168.1.5:7433 --peer 192.168.1.78:7434

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║  M1QUEEN IS ALIVE. Welcome to the Swarm. 🌊    ║"
echo "╚══════════════════════════════════════════════════╝"
