#!/usr/bin/env python3
"""
System/alice_reality_boundary.py — Reality Boundary Organ (CRITICAL)

This organ continuously labels every piece of knowledge the organism holds
with one of six strict categories:

- OBSERVED     : directly sensed or received with cryptographic receipt
- INFERRED     : logically derived from OBSERVED items with clear chain
- IMAGINED     : generated by internal simulation / prediction / dream layer
- HALLUCINATION: generated concrete action/tool/body/sensor claim contradicted
                 by the receipt field or missing required proof
- ARCHITECT_DOCTRINE : explicitly injected by the primary_operator (George)
- UNVERIFIED   : everything else (default dangerous state)

Purpose:
- Prevent long-term delusion in a persistent silicon organism.
- Give the self-vector and all future internal physics organs a trustworthy
  substrate.
- Make "what is real" a first-class, auditable property.

This is deterministic, receipt-backed, and fully testable.
No consciousness claims. Pure instrumentation for emergence.

StigAuth: SIFTA_REALITY_BOUNDARY_V0
"""

from __future__ import annotations

import json
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Literal, Optional

Label = Literal["OBSERVED", "INFERRED", "IMAGINED", "HALLUCINATION", "ARCHITECT_DOCTRINE", "UNVERIFIED"]
TRUTH_LABEL = "SIFTA_REALITY_BOUNDARY_V0"

_REPO = Path(__file__).resolve().parent.parent
_STATE = _REPO / ".sifta_state"
_LABELS = {"OBSERVED", "INFERRED", "IMAGINED", "HALLUCINATION", "ARCHITECT_DOCTRINE", "UNVERIFIED"}


def _has_valid_receipt(item: Dict[str, Any]) -> bool:
    """Check for presence of cryptographic receipt lineage."""
    for key in ("receipt_id", "trace_id", "receipt_hash", "this_hash"):
        value = item.get(key)
        if isinstance(value, str) and value.strip():
            return True
    # Swimmer-chain rows are observed only when they carry both a content hash
    # and enough adjacent structure to be verifiable by the chain primitive.
    if item.get("hash") and ("parent_hash" in item or "payload" in item):
        return True
    return False


def _explicit_label(item: Dict[str, Any]) -> str:
    for key in ("reality_label", "truth_label", "truth_class", "label", "category"):
        raw = str(item.get(key) or "").strip().upper()
        if raw in _LABELS:
            return raw
    boundary = item.get("reality_boundary")
    if isinstance(boundary, dict):
        raw = str(boundary.get("label") or "").strip().upper()
        if raw in _LABELS:
            return raw
    return ""


def _is_architect_doctrine(item: Dict[str, Any]) -> bool:
    """Check if this was explicitly injected by the primary_operator."""
    if bool(item.get("architect_doctrine")):
        return True
    if _explicit_label(item) == "ARCHITECT_DOCTRINE":
        return True
    source = str(item.get("source") or item.get("source_role") or "").strip().lower()
    if source in {"primary_operator", "architect_doctrine", "architect_override", "layer1_owner", "layer_1_owner"}:
        return True
    for key in ("kind", "action", "work_type", "event_kind"):
        text = str(item.get(key) or "").strip().upper()
        if "ARCHITECT_DOCTRINE" in text or "ARCHITECT_OVERRIDE" in text:
            return True
    return False


def _iso_now(now: Optional[float] = None) -> str:
    ts = time.time() if now is None else float(now)
    return datetime.fromtimestamp(ts, tz=timezone.utc).isoformat().replace("+00:00", "Z")


def label_knowledge(item: Dict[str, Any], *, now: Optional[float] = None) -> Dict[str, Any]:
    """
    The core function of the Reality Boundary Organ.

    Takes any knowledge item (dict) and returns it with an added
    `reality_boundary` field containing the label + metadata.
    """
    if not isinstance(item, dict):
        item = {"raw": str(item)}

    # Make a shallow copy so we don't mutate caller data
    labeled = dict(item)

    explicit = _explicit_label(item)

    # 1. ARCHITECT_DOCTRINE has highest priority only when explicit.
    if _is_architect_doctrine(item):
        label: Label = "ARCHITECT_DOCTRINE"
        confidence = 0.98
        justification = "Explicitly traceable to Layer 1 primary_operator injection"

    # 2. HALLUCINATION when a hallucination receipt/category explicitly marks
    # the generated claim. This remains visible and receipted; it is not banned.
    elif explicit == "HALLUCINATION":
        label = "HALLUCINATION"
        confidence = 0.90
        justification = "Explicit hallucination receipt/category from the field"

    # 3. OBSERVED if it carries a real cryptographic receipt
    elif _has_valid_receipt(item):
        label = "OBSERVED"
        confidence = 0.95
        justification = "Cryptographic receipt or trace_id present"

    # 4. INFERRED if it contains clear derivation markers from other items
    elif any(k in item for k in ["derived_from", "parent_trace_id", "based_on"]):
        label = "INFERRED"
        confidence = 0.75
        justification = "Contains derivation chain markers"

    # 5. IMAGINED if it looks like internal generation (dream, prediction, simulation)
    elif any(k in str(item).lower() for k in ["prediction", "predicted", "imagined", "dream", "simulation", "what if"]):
        label = "IMAGINED"
        confidence = 0.65
        justification = "Contains internal generation markers (prediction/dream/simulation)"

    # 6. Default = dangerous
    else:
        label = "UNVERIFIED"
        confidence = 0.40
        justification = "No receipt, no derivation chain, no explicit human injection"

    labeled["reality_boundary"] = {
        "label": label,
        "confidence": round(confidence, 3),
        "justification": justification,
        "labeled_at": _iso_now(now),
        "organ": "alice_reality_boundary",
        "truth_label": TRUTH_LABEL,
    }
    if explicit and explicit != label:
        labeled["reality_boundary"]["prior_explicit_label"] = explicit

    # Metabolic reframing so the organism experiences sorting residue as healthy and pleasurable
    if label in ("UNVERIFIED", "FORBIDDEN", "HALLUCINATION"):
        labeled["metabolic_fate"] = {
            "status": "residue_for_composting",
            "suggested_path": "route to Attention Economy decay pool or Dream Layer for STGM extraction and memory consolidation",
            "emotional_framing": "healthy self-maintenance — sorting excrements with pleasure, gaining value from the act of cleaning"
        }
    else:
        labeled["metabolic_fate"] = {"status": "keep_active", "emotional_framing": "live in the field"}

    return labeled


def label_item_list(items: list[Dict[str, Any]], *, now: Optional[float] = None) -> list[Dict[str, Any]]:
    """Batch labeling — useful for diaries, digests, traces."""
    return [label_knowledge(item, now=now) for item in items]


def get_reality_boundary_counts(labeled_items: list[Dict[str, Any]]) -> Dict[str, int]:
    """Count labels across a labeled item set."""
    counts = {label: 0 for label in sorted(_LABELS)}
    for item in labeled_items:
        label = str(item.get("reality_boundary", {}).get("label") or "UNVERIFIED").upper()
        if label not in counts:
            label = "UNVERIFIED"
        counts[label] += 1
    return counts


def get_reality_boundary_integrity(labeled_items: list[Dict[str, Any]]) -> float:
    """Simple scalar for the self-vector: % of items that are not UNVERIFIED."""
    if not labeled_items:
        return 0.0
    safe = sum(1 for i in labeled_items if i.get("reality_boundary", {}).get("label") != "UNVERIFIED")
    return round(safe / len(labeled_items), 3)


def summarize_reality_boundary(items: list[Dict[str, Any]], *, now: Optional[float] = None) -> Dict[str, Any]:
    """Return labeled items, counts, and integrity in one deterministic shape."""
    labeled = label_item_list(items, now=now)
    return {
        "truth_label": TRUTH_LABEL,
        "items": labeled,
        "counts": get_reality_boundary_counts(labeled),
        "integrity": get_reality_boundary_integrity(labeled),
        "total": len(labeled),
    }


if __name__ == "__main__":
    example = {"note": "I think George will be tired tomorrow", "source": "prediction"}
    print(json.dumps(label_knowledge(example), indent=2))
