#!/usr/bin/env python3
"""
System/stigmerobotics_e48_physical_protocol.py
===============================================

E48 — Physical Protocol Generation (Lab/Hardware Mapping)

ROB 501 topic: Bio-hybrid actuation — translating abstract control signals
into concrete hardware/wet-lab scripts.

Coverage: E33, E34, E38, E39, E45, E46, E47 specs → LabProtocol objects.
All generated scripts pass AST dry-run validation before returning.

Proof of Property (E48):
  - Every protocol enforces the E34 safety gate.
  - The protocol is deterministic (same spec → same steps).
  - Every script is AST-syntactically valid (dry-run validator built in).
  - Physical actuation stays HYPOTHESIS until lab receipt closes it.

truth_label: HYPOTHESIS (until run in the lab with real hardware receipts)
Covenant §7.11 / §7.2 / §8.6 absorption policy.
"""
from __future__ import annotations

import ast as _ast
from dataclasses import dataclass, field
from typing import Any

from System.stigmerobotics_wet_dry_interface import PhysicalEffectorSpec, wet_dry_bridge


# ── AST dry-run validator ─────────────────────────────────────────────────────

def _ast_validate(script: str, organ_id: str) -> tuple[bool, str]:
    """Parse *script* with the Python AST.  Returns (ok, detail)."""
    try:
        _ast.parse(script)
        return True, "AST parse OK"
    except SyntaxError as exc:
        return False, f"SyntaxError in {organ_id} script: {exc}"


@dataclass(frozen=True)
class LabProtocol:
    spec_organ_id: str
    hardware_target: str
    protocol_steps: tuple[str, ...]
    script_content: str
    safety_gate_enforced: bool
    truth_label: str = "HYPOTHESIS"
    ast_valid: bool = True
    ast_detail: str = "AST parse OK"

    @property
    def is_valid(self) -> bool:
        return self.safety_gate_enforced and len(self.protocol_steps) > 0 and self.ast_valid

    @property
    def proof_of_property(self) -> dict[str, Any]:
        return {
            "E48": "Physical Protocol Generation",
            "organ_id": self.spec_organ_id,
            "hardware_target": self.hardware_target,
            "steps": len(self.protocol_steps),
            "safety_gate_enforced": self.safety_gate_enforced,
            "ast_valid": self.ast_valid,
            "falsifier": "Protocol execution bypasses E34 safety gate OR script fails AST parse = BROKEN.",
            "truth_label": self.truth_label,
        }

def generate_protocol_for_spec(spec: PhysicalEffectorSpec) -> LabProtocol:
    """Map one PhysicalEffectorSpec → a deterministic, AST-validated LabProtocol.

    All scripts are HYPOTHESIS until run against real hardware with receipts.
    """
    base_steps = [
        "1. VERIFY SAFETY GATE: Check E34 registration edge for channel.",
        f"2. INITIALIZE HARDWARE for {spec.physical_name}.",
        f"3. EXECUTE MECHANISM: {spec.physical_mechanism[:80]}",
    ]
    script = f"# Autogenerated for {spec.organ_id}\ndef run_protocol():\n    pass\n"
    hardware_target = "Generic_WetLab"

    if spec.organ_id == "E33":
        hardware_target = "Opentrons_OT2"
        script = (
            "# Opentrons API v2 — E33 VLP Pheromone Field release\n"
            "# truth_label: HYPOTHESIS\n"
            "from opentrons import protocol_api\n"
            "metadata = {'apiLevel': '2.13'}\n"
            "def run(protocol: protocol_api.ProtocolContext):\n"
            "    # SAFETY GATE: E34 enforcement — external wrapper must confirm\n"
            "    plate = protocol.load_labware('corning_96_wellplate_360ul_flat', 1)\n"
            "    pipette = protocol.load_instrument('p300_single', 'right', tip_racks=[])\n"
            "    pipette.transfer(10, plate['A1'], plate['A2'])  # VLP pheromone release\n"
        )
        base_steps.append("4. DISPENSE VLP using Opentrons p300 single-channel.")
        base_steps.append("5. LOG dispensed volume to effector ledger (truth_label: HYPOTHESIS).")

    elif spec.organ_id == "E34":
        # E34: Safety-gated VLP cargo release — pH/optical trigger + plate-reader confirm
        hardware_target = "Opentrons_OT2_PlateReader"
        script = (
            "# Opentrons API v2 + plate-reader — E34 conditional VLP cargo release\n"
            "# truth_label: HYPOTHESIS\n"
            "from opentrons import protocol_api\n"
            "metadata = {'apiLevel': '2.13'}\n"
            "def run(protocol: protocol_api.ProtocolContext):\n"
            "    # SAFETY GATE: E34 — only release if safety edge is active\n"
            "    # Trigger: pH < 5.5 (endosomal escape) or optical pulse (660nm)\n"
            "    plate = protocol.load_labware('corning_96_wellplate_360ul_flat', 1)\n"
            "    tiprack = protocol.load_labware('opentrons_96_tiprack_300ul', 2)\n"
            "    pipette = protocol.load_instrument('p300_single', 'right', tip_racks=[tiprack])\n"
            "    # Step 1: Add trigger buffer (pH 5.0 acetate)\n"
            "    pipette.transfer(50, plate['A1'], plate['B1'])\n"
            "    protocol.delay(minutes=5, msg='Waiting for pH-triggered cargo release')\n"
            "    # Step 2: Plate-reader confirmation (absorbance 260nm — nucleic acid release)\n"
            "    # HUMAN_REVIEW_REQUIRED: confirm A260 > threshold before proceeding\n"
            "    pipette.transfer(10, plate['B1'], plate['C1'])  # Sample for confirmation\n"
        )
        base_steps.append("4. ADD pH trigger buffer (acetate pH 5.0) to wells.")
        base_steps.append("5. DELAY 5 min for endosomal-escape trigger.")
        base_steps.append("6. PLATE-READER confirmation A260 > threshold (HUMAN_REVIEW_REQUIRED).")
        base_steps.append("7. LOG release event to effector ledger (truth_label: HYPOTHESIS).")

    elif spec.organ_id == "E38":
        hardware_target = "Bioreactor_Assembly"
        script = (
            "# Bioreactor script — E38 Molecular Grammar (DFA-constrained CPMV assembly)\n"
            "# truth_label: HYPOTHESIS\n"
            "def run_bioreactor_assembly():\n"
            "    # SAFETY GATE: E34 enforcement\n"
            "    # State 1: Coat protein (CP) dimer formation — 4 deg C, 2h\n"
            "    # State 2: Pentamer assembly — 25 deg C, 1h\n"
            "    # State 3: Icosahedron closure — 37 deg C, 30min\n"
            "    # State 4: Cargo load / release — pH 5.5 trigger\n"
            "    pass  # DFA state transitions enforced by E38 automaton\n"
        )
        base_steps.append("4. INITIATE CP dimer formation (4°C, 120 min).")
        base_steps.append("5. WARM to 25°C — pentamer assembly (60 min).")
        base_steps.append("6. WARM to 37°C — icosahedron closure (30 min).")
        base_steps.append("7. DFA STATE CHECK: confirm state 4 before cargo load.")

    elif spec.organ_id == "E39":
        # E39: Steady-state VLP concentration — in-planta yield, spectrophotometry
        hardware_target = "Spectrophotometer_NanoDrop"
        script = (
            "# NanoDrop / UV-Vis — E39 Steady-State VLP Concentration\n"
            "# truth_label: HYPOTHESIS\n"
            "# Based on Saunders & Lomonossoff in-planta yield protocol\n"
            "def run_steady_state_yield_assay():\n"
            "    # SAFETY GATE: E34 enforcement\n"
            "    # Step 1: Harvest N. benthamiana leaves at 5 dpi\n"
            "    # Step 2: Grind in extraction buffer (PBS pH 7.4, 0.1% Tween-20)\n"
            "    # Step 3: Clarify by centrifugation (10,000 x g, 10 min, 4 deg C)\n"
            "    # Step 4: Measure A260 / A280 on NanoDrop — yield in mg/g fresh weight\n"
            "    # Step 5: Compare to ACO steady-state prediction from E39 organ\n"
            "    # HUMAN_REVIEW_REQUIRED: flag if yield < 0.1 mg/g FW (organ mismatch)\n"
            "    pass\n"
        )
        base_steps.append("4. HARVEST N. benthamiana leaves at 5 dpi.")
        base_steps.append("5. GRIND in PBS pH 7.4 + 0.1% Tween-20 extraction buffer.")
        base_steps.append("6. CLARIFY: centrifuge 10,000×g, 10 min, 4°C.")
        base_steps.append("7. NANODROP: measure A260/A280 → yield mg/g fresh weight.")
        base_steps.append("8. COMPARE to E39 ACO steady-state prediction; flag mismatch.")

    elif spec.organ_id == "E45":
        hardware_target = "Thermal_Cycler"
        script = (
            "# Thermal Cycler — E45 Brownian Wiggle (kT-bounded thermal noise)\n"
            "# truth_label: HYPOTHESIS\n"
            "def run_thermal_wiggle():\n"
            "    # SAFETY GATE: E34 enforcement\n"
            "    # Stokes-Einstein: D = kT / (6 * pi * eta * r)\n"
            "    # For 28nm VLP in water at 37 deg C: kT ≈ 4.28e-21 J\n"
            "    set_temperature = lambda t: None  # stub — replace with hardware call\n"
            "    set_temperature(37.0)  # physiological noise level\n"
            "    pass\n"
        )
        base_steps.append("4. SET temperature 37.0°C (physiological kT noise).")
        base_steps.append("5. HOLD 10 min — Brownian wiggle window.")
        base_steps.append("6. LOG diffusion coefficient estimate from E45 organ.")

    elif spec.organ_id == "E46":
        hardware_target = "Opentrons_OT2_Multi_Ligand"
        script = (
            "# Opentrons API v2 — E46b Segmental Phase-Angle Competitive Binding\n"
            "# truth_label: HYPOTHESIS\n"
            "from opentrons import protocol_api\n"
            "import math\n"
            "metadata = {'apiLevel': '2.13'}\n"
            "def run(protocol: protocol_api.ProtocolContext):\n"
            "    # SAFETY GATE: E34 enforcement per channel\n"
            "    plate = protocol.load_labware('corning_96_wellplate_360ul_flat', 1)\n"
            "    tiprack = protocol.load_labware('opentrons_96_tiprack_300ul', 2)\n"
            "    pipette = protocol.load_instrument('p300_single', 'right', tip_racks=[tiprack])\n"
            "    # Nearest-neighbor ring: phi_i = 2*pi*i/N\n"
            "    n_segments = 4\n"
            "    for i in range(n_segments):\n"
            "        phase = 2 * math.pi * i / n_segments\n"
            "        vol = 10 + int(5 * math.sin(phase))  # phase-modulated volume\n"
            "        pipette.transfer(vol, plate[f'A{i + 1}'], plate[f'B{i + 1}'])\n"
        )
        base_steps.append("4. DISPENSE phase-modulated ligand volumes (E46b ring topology).")
        base_steps.append("5. INCUBATE 30 min — competitive receptor binding.")
        base_steps.append("6. LOG binding competition result to effector ledger.")

    elif spec.organ_id == "E47":
        # E47: Biohybrid boundary — sanitize → quarantine → human-review gate
        hardware_target = "BioSafety_Cabinet_Class2"
        script = (
            "# Biosafety Cabinet Class II — E47 Biohybrid Boundary Protocol\n"
            "# truth_label: HYPOTHESIS\n"
            "def run_biohybrid_boundary_check():\n"
            "    # SAFETY GATE: E34 enforcement + E47 quarantine check\n"
            "    # Step 1: Sanitize all surfaces (70% EtOH, 15 min UV)\n"
            "    # Step 2: HUMAN_REVIEW_REQUIRED — researcher confirms sample identity\n"
            "    # Step 3: Sample isolation (sealed secondary containment)\n"
            "    # Step 4: Forbidden-key check (no live mammalian cells without GO)\n"
            "    # Step 5: Log clearance to effector ledger with PI signature\n"
            "    forbidden_keys = ['live_mammalian_cells', 'replication_competent_virus']\n"
            "    sample_keys = []  # populated from E47 spec at runtime\n"
            "    assert not any(k in sample_keys for k in forbidden_keys), 'E47 quarantine violation'\n"
        )
        base_steps.append("4. SANITIZE BSC (70% EtOH + 15 min UV) before sample handling.")
        base_steps.append("5. HUMAN_REVIEW_REQUIRED: PI confirms sample identity and containment.")
        base_steps.append("6. FORBIDDEN-KEY CHECK: no live mammalian cells or RCV without GO.")
        base_steps.append("7. LOG PI signature + clearance to effector ledger.")

    # AST dry-run validation — every generated script must parse
    ast_ok, ast_detail = _ast_validate(script, spec.organ_id)

    return LabProtocol(
        spec_organ_id=spec.organ_id,
        hardware_target=hardware_target,
        protocol_steps=tuple(base_steps),
        script_content=script,
        safety_gate_enforced=("E34" in spec.safety_gate_organ),
        ast_valid=ast_ok,
        ast_detail=ast_detail,
    )


def generate_all_protocols() -> list[LabProtocol]:
    """Generate LabProtocol for every spec in the wet-dry bridge."""
    bridge = wet_dry_bridge()
    return [generate_protocol_for_spec(spec) for spec in bridge.specs]


# ── ProtocolLibrary — index for organ-router queries ─────────────────────────

@dataclass
class ProtocolLibrary:
    """Index of all generated LabProtocols, queryable by organ ID.

    Used by the organ query router and the Stigmerobotics widget to give
    Alice deterministic answers about what physical protocols exist.
    """
    protocols: list[LabProtocol] = field(default_factory=list)

    def __post_init__(self) -> None:
        if not self.protocols:
            self.protocols = generate_all_protocols()

    def by_organ(self, organ_id: str) -> LabProtocol | None:
        """Return the protocol for *organ_id*, or None if not found."""
        organ_id = organ_id.upper()
        return next((p for p in self.protocols if p.spec_organ_id == organ_id), None)

    def all_valid(self) -> bool:
        """True if every protocol passes safety gate + AST validation."""
        return all(p.is_valid for p in self.protocols)

    def summary(self) -> str:
        lines = [f"E48 ProtocolLibrary — {len(self.protocols)} protocols:"]
        for p in self.protocols:
            status = "✅" if p.is_valid else "❌"
            lines.append(f"  {status} [{p.spec_organ_id}] {p.hardware_target} ({len(p.protocol_steps)} steps, AST:{p.ast_detail})")
        lines.append(f"All valid: {self.all_valid()}")
        return "\n".join(lines)

    def proof_of_property(self) -> dict[str, Any]:
        return {
            "E48": "ProtocolLibrary",
            "total_protocols": len(self.protocols),
            "all_valid": self.all_valid(),
            "coverage": [p.spec_organ_id for p in self.protocols],
            "all_ast_valid": all(p.ast_valid for p in self.protocols),
            "falsifier": "any p.is_valid==False or p.ast_valid==False = E48 BROKEN",
            "truth_label": "HYPOTHESIS",
        }


if __name__ == "__main__":
    lib = ProtocolLibrary()
    print(lib.summary())
    print()
    print("proof_of_property:", lib.proof_of_property())

