#!/usr/bin/env python3
"""
System/swarm_truth_label_canon.py — Canonical truth-label registry
====================================================================
StigAuth: SIFTA_TRUTH_LABEL_CANON_V0

Architect 2026-05-16: *"be careful of the others because sometimes they
make up organs ... we already have most of this it's just not wired
properly."* (Cowork CW47 / Claude, surgery ``cw47-0516-2236``.)

The covenant defines a strict set of truth labels at §7.10.1 + §7.11:

    OBSERVED            — sensor / receipt / probed fact
    OPERATIONAL         — system behaves as designed; receipt-backed
    HYPOTHESIS          — proposed but not yet receipt-verified
    ARCHITECT_DOCTRINE  — Architect-held stance (not a receipt)
    FORBIDDEN           — forged tools, fake sensors, invented claims

Peer doctors have introduced alternative vocabulary (``INFERRED``,
``IMAGINED``, ``UNVERIFIED``) in standalone organs. This registry maps
those aliases back to the canonical labels so the swarm converges
instead of fragmenting. It is **read-only** and has zero side effects.

This module also provides :func:`is_architect_doctrine`, which checks
whether an item carries an explicit doctrine marker — including a
runtime-loaded owner_name from ``owner_genesis.json``. The owner name
is **never** hardcoded; that is the Layer-1 invariant the Architect
named.

Truth label of this module: ``SIFTA_TRUTH_LABEL_CANON_V0``.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Iterable, Optional, Tuple

_REPO = Path(__file__).resolve().parent.parent
_GENESIS_DEFAULT = _REPO / ".sifta_state" / "owner_genesis.json"

TRUTH_LABEL = "SIFTA_TRUTH_LABEL_CANON_V0"

# Covenant-canonical labels (§7.10.1 + §7.11). Ordering reflects
# epistemic strength: leftmost = strongest, rightmost = weakest /
# explicitly invalid.
CANONICAL_LABELS: Tuple[str, ...] = (
    "OBSERVED",
    "OPERATIONAL",
    "HYPOTHESIS",
    "ARCHITECT_DOCTRINE",
    "FORBIDDEN",
)
CANONICAL_SET = frozenset(CANONICAL_LABELS)

# Peer-introduced aliases → canonical mapping. Each entry preserves the
# intent of the alias while routing to the canonical label so downstream
# consumers see one vocabulary.
ALIAS_MAP: Dict[str, str] = {
    # Grok's alice_reality_boundary.py 2026-05-16 vocabulary
    "INFERRED": "HYPOTHESIS",   # logically derived → not yet receipt-verified
    "IMAGINED": "HYPOTHESIS",   # generated by internal simulation
    "UNVERIFIED": "HYPOTHESIS", # default-unsafe → still a hypothesis until proven
    # Common shorthand
    "OBSERVED_FACT": "OBSERVED",
    "OBSERVATIONAL": "OBSERVED",
    "PROBED": "OBSERVED",
    "RECEIPTED": "OBSERVED",
    "OPERATIONAL_FACT": "OPERATIONAL",
    "WORKING": "OPERATIONAL",
    "HYPOTHETICAL": "HYPOTHESIS",
    "PROPOSED": "HYPOTHESIS",
    "PREDICTED": "HYPOTHESIS",
    "DREAMED": "HYPOTHESIS",
    "INVENTED": "HYPOTHESIS",
    "ARCHITECT_HELD": "ARCHITECT_DOCTRINE",
    "DOCTRINE": "ARCHITECT_DOCTRINE",
    "DECREE": "ARCHITECT_DOCTRINE",
    "FORGED": "FORBIDDEN",
    "FAKE": "FORBIDDEN",
    "HALLUCINATED": "FORBIDDEN",
    "FABRICATED": "FORBIDDEN",
}

# Markers that an item carries an explicit Architect-doctrine signal.
# Owner_name is read from owner_genesis.json at runtime — NEVER hardcoded.
_DOCTRINE_MARKERS: Tuple[str, ...] = (
    "ARCHITECT_DOCTRINE",
    "architect_doctrine",
    "primary_operator",
    "§7.13",
    "§7.10.2",
    "§7.11",
    "architect_quote",
    "architect_whatsapp_quote",
    "architect_authorization",
)

DEFAULT_LABEL = "HYPOTHESIS"  # safe default when nothing else fits


def normalise_label(value: Any) -> str:
    """Map ``value`` to a canonical covenant truth label.

    * Canonical labels pass through (case-normalised).
    * Known aliases route per :data:`ALIAS_MAP`.
    * Unknown values fall back to :data:`DEFAULT_LABEL` (``HYPOTHESIS``),
      which the covenant treats as the safe-pending state.
    """
    s = str(value or "").strip().upper().replace("-", "_").replace(" ", "_")
    if s in CANONICAL_SET:
        return s
    if s in ALIAS_MAP:
        return ALIAS_MAP[s]
    return DEFAULT_LABEL


def _load_owner_name(genesis_path: Optional[Path] = None) -> str:
    """Read the canonical owner_name from ``owner_genesis.json`` at
    runtime. Returns ``""`` if the file is missing or malformed.
    NEVER hardcoded.
    """
    path = Path(genesis_path) if genesis_path is not None else _GENESIS_DEFAULT
    if not path.exists():
        return ""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return ""
    if not isinstance(data, dict):
        return ""
    return str(data.get("owner_name") or "").strip()


def is_architect_doctrine(
    item: Any,
    *,
    genesis_path: Optional[Path] = None,
) -> bool:
    """True when ``item`` explicitly carries an Architect-doctrine marker
    or names the owner directly.

    The owner_name comparison reads the canonical name from
    ``owner_genesis.json`` at runtime; this module contains zero
    hardcoded owner names.
    """
    try:
        # ensure_ascii=False so the §-section markers (§7.13 / §7.10.2 /
        # §7.11) survive the JSON serialisation step and remain
        # detectable by the marker scan below.
        blob = json.dumps(item, default=str, ensure_ascii=False).lower()
    except Exception:
        blob = str(item).lower()
    for marker in _DOCTRINE_MARKERS:
        if marker.lower() in blob:
            return True
    owner = _load_owner_name(genesis_path).lower()
    if owner and owner in blob:
        return True
    return False


def label_kind(value: Any) -> Dict[str, Any]:
    """Convenience: return a triple ``{raw, canonical, was_alias}`` for
    instrumentation / digests. ``was_alias`` is True when the raw value
    was recognised as an alias and remapped.
    """
    raw = str(value or "").strip()
    canon = normalise_label(value)
    upper = raw.upper().replace("-", "_").replace(" ", "_")
    was_alias = bool(upper and upper not in CANONICAL_SET and upper in ALIAS_MAP)
    return {"raw": raw, "canonical": canon, "was_alias": was_alias}


def list_aliases_for(label: str) -> Tuple[str, ...]:
    """Return every alias that maps to ``label`` (canonical input)."""
    label = label.upper()
    if label not in CANONICAL_SET:
        return ()
    return tuple(sorted(k for k, v in ALIAS_MAP.items() if v == label))


__all__ = [
    "ALIAS_MAP",
    "CANONICAL_LABELS",
    "CANONICAL_SET",
    "DEFAULT_LABEL",
    "TRUTH_LABEL",
    "is_architect_doctrine",
    "label_kind",
    "list_aliases_for",
    "normalise_label",
]
