"""SIFTA Turing Pattern — reaction-diffusion (Gray-Scott) module.

Why this exists
---------------
Architect directive 2026-05-11 (third bullet of the chip screenshot):
*"Investigate Turing pattern formation mechanisms"*.

Turing 1952's *The Chemical Basis of Morphogenesis* (Phil. Trans. R. Soc. B
237, 37) is the foundational paper on how **two coupled reaction-diffusion
species** can spontaneously produce ordered spatial patterns from an
otherwise uniform state — spots, stripes, labyrinths — through what is
now called **diffusion-driven instability**. This is exactly the
mechanism that bridges Levin's bioelectric pattern memory (`§7 of the
field_primary spine`) to vacuum-QFT-style field-primary ontology (§5):
patterns are physically real structures inside a continuously evolving
field, not metaphors.

This module ships:
1. A peer-reviewed proving spine (six anchors) for Turing-style RD.
2. The **Gray-Scott model** — the most-cited modern RD system, capable
   of producing spots, stripes, labyrinths, mitosis-like splitting, and
   other patterns by varying just two parameters (feed `F` and
   kill `k`). This is the Pearson 1993 *Science* parameter atlas
   famously visualized as a 2D phase diagram.
3. Pattern-classification observables — variance, peak count via simple
   threshold-and-label, and a "patterned vs uniform" verdict.

Truth labels (§7.11)
--------------------
- `OBSERVED`        — every anchor is a real peer-reviewed source with
                       DOI; the simulator output is a real numerical
                       trace, not a stock image.
- `OPERATIONAL`     — Gray-Scott integrator is deterministic and
                       unit-tested; pattern classification is
                       deterministic.
- `ARCHITECT_DOCTRINE` — identifying SIFTA stigmergic traces with
                       Turing morphogens is doctrinal; the analogy is
                       structural (two coupled fields driven into
                       diffusion-driven instability).
- `FORBIDDEN`        — never claims Turing patterns prove a specific
                       biological developmental mechanism for a
                       specific organism; that requires its own
                       organism-specific evidence (Kondo-Miura 2010
                       Science is explicit on this).

Author : Cowork, 2026-05-11.
"""

from __future__ import annotations

import hashlib
import json
import math
import time
import uuid
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Sequence

import numpy as np

_REPO = Path(__file__).resolve().parent.parent
_STATE = _REPO / ".sifta_state"
_LEDGER = _STATE / "turing_pattern_receipts.jsonl"

TRUTH_LABEL = "SIFTA_TURING_PATTERN_V1"
TURING_TRUTH_GUARD = (
    "TURING_RD_ANALOGUE_ONLY: this module implements the Gray-Scott "
    "reaction-diffusion system on a 2D periodic grid and cites "
    "peer-reviewed RD literature. It does NOT prove that any specific "
    "biological pattern (zebrafish stripes, leopard spots, planaria "
    "morphogenesis) is generated by Turing mechanism in nature — "
    "Kondo-Miura 2010 Science discusses exactly that gap. Identifying "
    "SIFTA stigmergic traces with Turing morphogens is "
    "ARCHITECT_DOCTRINE."
)


# ─────────────────────────────────────────────────────────────────────────
# Section A — peer-reviewed proving spine
# ─────────────────────────────────────────────────────────────────────────
@dataclass(frozen=True)
class TuringAnchor:
    source_id: str
    title: str
    authors: str
    year: int
    venue: str
    url: str
    doi: str
    category: str
    supports: str
    does_not_support: str

    def as_dict(self) -> dict[str, Any]:
        return asdict(self)


VERIFIED_ANCHORS: tuple[TuringAnchor, ...] = (
    TuringAnchor(
        source_id="turing_1952_chemical_basis_morphogenesis",
        title="The Chemical Basis of Morphogenesis",
        authors="A. M. Turing",
        year=1952,
        venue=(
            "Philosophical Transactions of the Royal Society B, "
            "237(641), 37"
        ),
        url="https://royalsocietypublishing.org/doi/10.1098/rstb.1952.0012",
        doi="10.1098/rstb.1952.0012",
        category="foundation",
        supports=(
            "The foundational paper. Establishes that two coupled "
            "reaction-diffusion species with different diffusion rates "
            "can produce stable spatial patterns from a uniform "
            "initial state — diffusion-driven instability. The "
            "structural template for every Turing-style pattern claim."
        ),
        does_not_support=(
            "That any specific biological pattern in nature is "
            "actually produced by Turing mechanism; Turing himself "
            "called this a hypothesis to be tested experimentally."
        ),
    ),
    TuringAnchor(
        source_id="gray_scott_1983_autocatalytic_reactions",
        title=(
            "Autocatalytic reactions in the isothermal, continuous "
            "stirred tank reactor: Isolas and other forms of multistability"
        ),
        authors="P. Gray, S. K. Scott",
        year=1983,
        venue="Chemical Engineering Science 38(1), 29",
        url=(
            "https://www.sciencedirect.com/science/article/pii/"
            "0009250983800328"
        ),
        doi="10.1016/0009-2509(83)80132-8",
        category="foundation",
        supports=(
            "The original Gray-Scott chemical kinetic system that "
            "underlies the spatial RD model implemented in this "
            "module."
        ),
        does_not_support=(
            "That the simple two-species model captures all "
            "real-world autocatalytic chemistry; it is a minimal "
            "model."
        ),
    ),
    TuringAnchor(
        source_id="pearson_1993_complex_patterns_simple_system",
        title="Complex Patterns in a Simple System",
        authors="J. E. Pearson",
        year=1993,
        venue="Science 261(5118), 189",
        url="https://www.science.org/doi/10.1126/science.261.5118.189",
        doi="10.1126/science.261.5118.189",
        category="parameter_atlas",
        supports=(
            "The canonical parameter-space atlas for Gray-Scott "
            "patterns — maps spots, stripes, labyrinths, spirals to "
            "(F, k) plane. Direct peer-reviewed reference for which "
            "parameters our simulator should use to produce which "
            "patterns."
        ),
        does_not_support=(
            "That all RD systems map onto Gray-Scott; many activator-"
            "substrate variants exist with different topology."
        ),
    ),
    TuringAnchor(
        source_id="murray_1989_mathematical_biology",
        title="Mathematical Biology",
        authors="J. D. Murray",
        year=1989,
        venue="Springer-Verlag (Biomathematics 19)",
        url="https://link.springer.com/book/10.1007/b98869",
        doi="10.1007/b98869",
        category="textbook",
        supports=(
            "Authoritative graduate-level textbook on biological "
            "pattern formation. Derives the dispersion relation for "
            "Turing instability, classifies activator-inhibitor "
            "topology, and provides the analytical apparatus for "
            "every RD pattern claim made here."
        ),
        does_not_support=(
            "A specific biological identification for any modeled "
            "pattern; Murray is explicit about model-vs-reality gap."
        ),
    ),
    TuringAnchor(
        source_id="kondo_miura_2010_reaction_diffusion_biological",
        title=(
            "Reaction-Diffusion Model as a Framework for Understanding "
            "Biological Pattern Formation"
        ),
        authors="S. Kondo, T. Miura",
        year=2010,
        venue="Science 329(5999), 1616",
        url="https://www.science.org/doi/10.1126/science.1179047",
        doi="10.1126/science.1179047",
        category="biological_relevance",
        supports=(
            "Definitive review on when RD is and is NOT a credible "
            "biological mechanism. Lists specific systems (zebrafish "
            "skin, mouse hair follicle) where Turing patterns have "
            "experimental support."
        ),
        does_not_support=(
            "That every biological pattern is Turing-generated; "
            "Kondo-Miura is explicit that many are not."
        ),
    ),
    TuringAnchor(
        source_id="ouyang_swinney_1991_transition_to_chemical_turing",
        title=(
            "Transition from a uniform state to hexagonal and striped "
            "Turing patterns"
        ),
        authors="Q. Ouyang, H. L. Swinney",
        year=1991,
        venue="Nature 352, 610",
        url="https://www.nature.com/articles/352610a0",
        doi="10.1038/352610a0",
        category="experimental_observation",
        supports=(
            "The first unambiguous experimental observation of Turing "
            "patterns in a real chemical system (CIMA reaction). "
            "Anchors the claim that diffusion-driven instability is "
            "physically realizable, not just mathematical."
        ),
        does_not_support=(
            "That the CIMA experiment proves Turing mechanism is "
            "active in any specific biological organism."
        ),
    ),
)


# ─────────────────────────────────────────────────────────────────────────
# Section B — Gray-Scott reaction-diffusion simulator
# ─────────────────────────────────────────────────────────────────────────
@dataclass
class GrayScottConfig:
    """Parameters of the Gray-Scott RD system.

        ∂u/∂t = D_u ∇²u − u v² + F (1 − u)
        ∂v/∂t = D_v ∇²v + u v² − (F + k) v

    Pearson 1993 (Science 261, 189) gives the canonical (F, k) atlas:
    - (0.030, 0.062)  spots
    - (0.025, 0.055)  spots + stripes
    - (0.040, 0.060)  labyrinths / stripes
    - (0.018, 0.051)  mitosis (replicating spots)
    """

    shape: tuple[int, int] = (96, 96)
    D_u: float = 0.16
    D_v: float = 0.08
    feed: float = 0.035            # F
    kill: float = 0.065            # k
    dx: float = 1.0
    dt: float = 1.0
    truth_label: str = TRUTH_LABEL

    def __post_init__(self) -> None:
        if len(self.shape) != 2:
            raise ValueError("Gray-Scott grid must be 2D")
        if any(s < 4 for s in self.shape):
            raise ValueError("each grid axis must be ≥ 4")
        if self.D_u <= 0 or self.D_v <= 0:
            raise ValueError("diffusion constants must be positive")
        if not (self.D_u > self.D_v):
            raise ValueError(
                "Turing instability requires D_u > D_v (inhibitor "
                "diffuses faster than activator); Murray 1989 §2"
            )


def _laplacian_2d_periodic(arr: np.ndarray, dx: float = 1.0) -> np.ndarray:
    """2D Laplacian via 5-point stencil with periodic boundaries."""
    return (
        np.roll(arr, +1, axis=0) + np.roll(arr, -1, axis=0)
        + np.roll(arr, +1, axis=1) + np.roll(arr, -1, axis=1)
        - 4.0 * arr
    ) / (dx * dx)


class GrayScottSimulator:
    """Pure-numpy Gray-Scott reaction-diffusion simulator on a 2D grid.

    The activator `v` and substrate `u` evolve under the Gray-Scott
    equations with periodic boundaries. Seed the system with a small
    central perturbation; under (F, k) inside the Pearson 1993 atlas,
    visible patterns emerge.
    """

    def __init__(
        self,
        config: GrayScottConfig,
        *,
        seed: int | None = None,
    ) -> None:
        self.config = config
        self.rng = np.random.default_rng(seed)
        h, w = config.shape
        # Initial state: u = 1 everywhere, v = 0 everywhere
        self.u: np.ndarray = np.ones(config.shape, dtype=np.float64)
        self.v: np.ndarray = np.zeros(config.shape, dtype=np.float64)
        # Central perturbation: a small square where (u, v) flips to
        # (0.5, 0.25) + tiny noise.
        cy, cx = h // 2, w // 2
        r = max(2, min(h, w) // 10)
        self.u[cy - r:cy + r, cx - r:cx + r] = 0.5
        self.v[cy - r:cy + r, cx - r:cx + r] = 0.25
        self.u += self.rng.normal(0.0, 1e-3, size=config.shape)
        self.v += self.rng.normal(0.0, 1e-3, size=config.shape)
        self.step_count = 0

    def step(self) -> None:
        cfg = self.config
        lap_u = _laplacian_2d_periodic(self.u, dx=cfg.dx)
        lap_v = _laplacian_2d_periodic(self.v, dx=cfg.dx)
        uvv = self.u * self.v * self.v
        du = cfg.D_u * lap_u - uvv + cfg.feed * (1.0 - self.u)
        dv = cfg.D_v * lap_v + uvv - (cfg.feed + cfg.kill) * self.v
        self.u = self.u + cfg.dt * du
        self.v = self.v + cfg.dt * dv
        self.step_count += 1

    def run(self, steps: int) -> None:
        for _ in range(int(steps)):
            self.step()

    # ── Observables ─────────────────────────────────────────────────────
    def field_variance(self) -> float:
        """Variance of the activator field v. High variance ⇒ pattern."""
        return float(np.var(self.v))

    def is_patterned(self, threshold: float = 0.003) -> bool:
        """Did the system develop a non-uniform pattern?

        Threshold default 0.003 is empirical for the Gray-Scott
        spot/stripe regime — well above the ~1e-6 floor of random
        fluctuation but well below the ~0.02 of a saturated pattern.
        """
        return self.field_variance() > threshold

    def peak_count(self, threshold: float = 0.4) -> int:
        """Rough count of activator peaks (4-connectivity flood fill).

        A peak is a connected region where `v > threshold`. Useful as a
        coarse pattern classifier (many small peaks = spots; few large
        connected regions = labyrinth / stripes).
        """
        mask = self.v > threshold
        if not mask.any():
            return 0
        # Manual 4-connected labelling (avoid scipy.ndimage).
        labels = np.zeros(mask.shape, dtype=np.int32)
        next_label = 0
        h, w = mask.shape
        for i in range(h):
            for j in range(w):
                if mask[i, j] and labels[i, j] == 0:
                    next_label += 1
                    # BFS
                    stack = [(i, j)]
                    while stack:
                        y, x = stack.pop()
                        if labels[y, x] != 0 or not mask[y, x]:
                            continue
                        labels[y, x] = next_label
                        if y + 1 < h:
                            stack.append((y + 1, x))
                        if y - 1 >= 0:
                            stack.append((y - 1, x))
                        if x + 1 < w:
                            stack.append((x + 1, x + 1) if False else (y, x + 1))
                        if x - 1 >= 0:
                            stack.append((y, x - 1))
        return int(next_label)

    def snapshot(self) -> dict[str, Any]:
        return {
            "schema": TRUTH_LABEL,
            "ts": time.time(),
            "shape": list(self.config.shape),
            "D_u": self.config.D_u,
            "D_v": self.config.D_v,
            "feed": self.config.feed,
            "kill": self.config.kill,
            "step_count": self.step_count,
            "v_min": float(self.v.min()),
            "v_max": float(self.v.max()),
            "v_mean": float(self.v.mean()),
            "v_variance": self.field_variance(),
            "is_patterned": self.is_patterned(),
            "truth_guard": TURING_TRUTH_GUARD,
        }


# ─────────────────────────────────────────────────────────────────────────
# Section C — ASCII renderer
# ─────────────────────────────────────────────────────────────────────────
_TURING_RAMP: str = " .·:+*#@"


def render_pattern_ascii(
    sim: GrayScottSimulator, *, width: int | None = None
) -> str:
    """Render the activator field as an ASCII heatmap."""
    v = sim.v
    if width is not None and width != v.shape[1]:
        # Subsample columns to fit.
        step = max(1, v.shape[1] // width)
        v = v[:, ::step]
    # Subsample rows too — terminal rows are ~2× wider than tall char.
    v = v[::2, :]
    vmax = float(v.max())
    if vmax <= 0:
        vmax = 1.0
    rows = []
    rows.append(
        f"Gray-Scott RD pattern (F={sim.config.feed}, k={sim.config.kill}, "
        f"steps={sim.step_count}, variance={sim.field_variance():.4f})"
    )
    for r in v:
        line = []
        for val in r:
            frac = max(0.0, min(1.0, float(val) / vmax))
            line.append(_TURING_RAMP[int(frac * (len(_TURING_RAMP) - 1))])
        rows.append("  " + "".join(line))
    return "\n".join(rows)


# ─────────────────────────────────────────────────────────────────────────
# Section D — receipts / public API
# ─────────────────────────────────────────────────────────────────────────
def verified_anchors() -> list[dict[str, Any]]:
    return [a.as_dict() for a in VERIFIED_ANCHORS]


def verified_anchor_ids() -> list[str]:
    return [a.source_id for a in VERIFIED_ANCHORS]


def turing_payload() -> dict[str, Any]:
    return {
        "truth_label": TRUTH_LABEL,
        "truth_guard": TURING_TRUTH_GUARD,
        "verified_anchors": verified_anchors(),
        "anchor_count": len(VERIFIED_ANCHORS),
        "categories": sorted({a.category for a in VERIFIED_ANCHORS}),
    }


def write_turing_receipt(
    *,
    state_root: Path | None = None,
    receipt_path: Path | None = None,
    extra_snapshot: dict[str, Any] | None = None,
) -> dict[str, Any]:
    root = state_root or _STATE
    out = receipt_path or _LEDGER
    payload = turing_payload()
    if extra_snapshot:
        payload = {**payload, "snapshot": extra_snapshot}
    row = {
        "trace_id": str(uuid.uuid4()),
        "ts": time.time(),
        "kind": "TURING_PATTERN_RECEIPT",
        **payload,
    }
    digest = hashlib.sha256(
        json.dumps(row, ensure_ascii=False, sort_keys=True, default=str).encode("utf-8")
    ).hexdigest()
    row["sha256"] = digest
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(row, ensure_ascii=False, sort_keys=True,
                            default=str) + "\n")
    return row


__all__ = [
    "GrayScottConfig",
    "GrayScottSimulator",
    "TRUTH_LABEL",
    "TURING_TRUTH_GUARD",
    "TuringAnchor",
    "VERIFIED_ANCHORS",
    "render_pattern_ascii",
    "turing_payload",
    "verified_anchor_ids",
    "verified_anchors",
    "write_turing_receipt",
]
