#!/usr/bin/env python3
"""swarm_speech_game_sentence_corpus.py — real-sentence proposer for the
Stigmergic Speech Game.

StigAuth: ``SIFTA_SPEECH_GAME_SENTENCE_CORPUS_V0``

Architect constraint (2026-05-17, verbatim):

  *"the sentence has to has to be not make up stuff we don't want any
  hallucination stuff to talk about anything that is not real or it's
  not related to us here to the computer or something ... they should
  we should be about real things not made that stuff"*

This organ proposes sentences pulled exclusively from REAL local
sources so the Speech Game never asks the human to invent material:

  1. Architect memory digests   (``Documents/architect_memory_digest/*.md``)
  2. Today's Alice journal      (``.sifta_state/alice_journal/<YYYY-MM-DD>.jsonl``)
  3. Recent conversation tail   (``.sifta_state/alice_conversation.jsonl``)
  4. Live apps manifest         (``Applications/apps_manifest.json`` descriptions)

Each returned sentence carries provenance (source kind + file path +
extracted span) so the round receipt in
``.sifta_state/speech_game_rounds.jsonl`` can be audited end-to-end.
Nothing is invented; nothing is generated by a language model.

Covenant alignment:
  * §6  — effector truth: each sentence has a verifiable source row.
  * §7.2 — tool truth: deterministic, append-only, receipt-able.
  * §7.10.1 — Layer-1: owner_name (if needed) is read from
    ``owner_genesis.json`` at runtime, not hardcoded.

Co-doctor narrowing of Grok's ``cw47-0517-0250`` Speech Organ lane.
Cowork CW47 / Claude surgery cw47-0517-0312, 2026-05-17.
"""
from __future__ import annotations

import json
import random
import re
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Dict, Iterable, List, Optional

_REPO = Path(__file__).resolve().parent.parent
_STATE = _REPO / ".sifta_state"
_JOURNAL_DIR = _STATE / "alice_journal"
_CONVERSATION = _STATE / "alice_conversation.jsonl"
_DIGESTS_DIR = _REPO / "Documents" / "architect_memory_digest"
_APPS_MANIFEST = _REPO / "Applications" / "apps_manifest.json"

TRUTH_LABEL = "SIFTA_SPEECH_GAME_SENTENCE_CORPUS_V0"

# Word-count bounds — short enough to read out loud easily, long enough
# that STT can fail in interesting ways. Architect game design implies
# "short sentences" / "tongue twisters" → 4–14 tokens.
MIN_WORDS = 4
MAX_WORDS = 14

# Strip lines that look like ledger rows, trace IDs, URLs, or emoji-only
# noise — those are not natural spoken sentences.
_REJECT_PATTERNS = (
    re.compile(r"\bcw47-\d{4}-\d{4}\b", re.IGNORECASE),   # surgery IDs
    re.compile(r"https?://"),                              # URLs
    re.compile(r"[A-F0-9]{8,}\b", re.IGNORECASE),          # SHA / UUID frags
    re.compile(r"^\s*[`\-*#>•]+\s*$"),                     # md decoration
    re.compile(r"\.(?:jsonl?|md|py|html?)\b", re.IGNORECASE),
    re.compile(r"\bSTGM[_ ]?\d+\b"),                       # token amounts
    re.compile(r"\bGTH4921YP3\b"),                         # node serial
)

# Sentence-boundary splitter that tolerates abbreviations modestly.
_SENT_SPLIT = re.compile(r"(?<=[.!?])\s+(?=[A-Z\"'(])")


@dataclass(frozen=True)
class RealSentence:
    text: str
    source_kind: str              # "digest" | "journal" | "conversation" | "manifest"
    source_path: str
    word_count: int
    sampled_ts: float = field(default_factory=time.time)
    truth_label: str = TRUTH_LABEL

    def to_dict(self) -> Dict[str, str]:
        return asdict(self)


# ── extractors ───────────────────────────────────────────────────────────


def _count_words(text: str) -> int:
    return len([w for w in re.findall(r"\b\w+\b", text)])


def _passes_filters(text: str) -> bool:
    s = (text or "").strip()
    if not s:
        return False
    n = _count_words(s)
    if n < MIN_WORDS or n > MAX_WORDS:
        return False
    for pat in _REJECT_PATTERNS:
        if pat.search(s):
            return False
    # Must contain at least one verb-ish lowercase letter sequence — pure
    # noun-phrase fragments aren't natural sentences.
    if not re.search(r"[a-z]{2,}", s):
        return False
    return True


def _split_into_sentences(blob: str) -> List[str]:
    if not blob:
        return []
    rough = _SENT_SPLIT.split(blob.replace("\n", " "))
    out = []
    for piece in rough:
        piece = re.sub(r"\s+", " ", piece).strip(" \t\"'`")
        if piece:
            out.append(piece)
    return out


def _harvest_digests() -> Iterable[RealSentence]:
    if not _DIGESTS_DIR.exists():
        return
    for p in sorted(_DIGESTS_DIR.glob("*.md"), reverse=True)[:8]:
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for sent in _split_into_sentences(text):
            if _passes_filters(sent):
                yield RealSentence(
                    text=sent,
                    source_kind="digest",
                    source_path=str(p.relative_to(_REPO)),
                    word_count=_count_words(sent),
                )


def _harvest_journal_today() -> Iterable[RealSentence]:
    if not _JOURNAL_DIR.exists():
        return
    today = time.strftime("%Y-%m-%d", time.localtime())
    journal = _JOURNAL_DIR / f"{today}.jsonl"
    if not journal.exists():
        # Fall back to the most recent journal file.
        candidates = sorted(_JOURNAL_DIR.glob("*.jsonl"), reverse=True)
        if not candidates:
            return
        journal = candidates[0]
    try:
        lines = journal.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError:
        return
    for raw in lines[-200:]:
        raw = raw.strip()
        if not raw:
            continue
        try:
            row = json.loads(raw)
        except json.JSONDecodeError:
            continue
        if not isinstance(row, dict):
            continue
        for key in ("alice_entry", "owner_text", "note", "text", "summary"):
            blob = row.get(key)
            if isinstance(blob, str):
                for sent in _split_into_sentences(blob):
                    if _passes_filters(sent):
                        yield RealSentence(
                            text=sent,
                            source_kind="journal",
                            source_path=str(journal.relative_to(_REPO)),
                            word_count=_count_words(sent),
                        )


def _harvest_conversation_tail() -> Iterable[RealSentence]:
    if not _CONVERSATION.exists():
        return
    try:
        with _CONVERSATION.open("rb") as f:
            f.seek(0, 2)
            end = f.tell()
            f.seek(max(0, end - 64 * 1024))
            tail = f.read().decode("utf-8", errors="replace")
    except OSError:
        return
    for raw in tail.splitlines()[-200:]:
        raw = raw.strip()
        if not raw:
            continue
        try:
            row = json.loads(raw)
        except json.JSONDecodeError:
            continue
        if not isinstance(row, dict):
            continue
        # Only owner turns — Alice's prose is allowed to be more florid;
        # owner speech is what we want to ground the game in.
        if (row.get("role") or "").lower() not in ("user", "owner", "george"):
            continue
        text = row.get("content") or row.get("text") or ""
        if isinstance(text, str):
            for sent in _split_into_sentences(text):
                if _passes_filters(sent):
                    yield RealSentence(
                        text=sent,
                        source_kind="conversation",
                        source_path=str(_CONVERSATION.relative_to(_REPO)),
                        word_count=_count_words(sent),
                    )


def _harvest_manifest_descriptions() -> Iterable[RealSentence]:
    if not _APPS_MANIFEST.exists():
        return
    try:
        manifest = json.loads(_APPS_MANIFEST.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return
    if not isinstance(manifest, dict):
        return
    for app_name, entry in manifest.items():
        if not isinstance(entry, dict):
            continue
        desc = entry.get("description") or entry.get("tagline") or ""
        if isinstance(desc, str):
            for sent in _split_into_sentences(desc):
                if _passes_filters(sent):
                    yield RealSentence(
                        text=sent,
                        source_kind="manifest",
                        source_path=str(_APPS_MANIFEST.relative_to(_REPO)),
                        word_count=_count_words(sent),
                    )


# ── public API ───────────────────────────────────────────────────────────


def harvest_all(
    *,
    sources: Optional[Iterable[str]] = None,
) -> List[RealSentence]:
    """Collect every real sentence from every requested source.

    ``sources`` filters to a subset of {"digest", "journal", "conversation",
    "manifest"}. ``None`` means all four.
    """
    wanted = set(sources or ("digest", "journal", "conversation", "manifest"))
    out: List[RealSentence] = []
    if "digest" in wanted:
        out.extend(_harvest_digests())
    if "journal" in wanted:
        out.extend(_harvest_journal_today())
    if "conversation" in wanted:
        out.extend(_harvest_conversation_tail())
    if "manifest" in wanted:
        out.extend(_harvest_manifest_descriptions())
    # Deduplicate by lowercased text but preserve first-seen provenance.
    seen = set()
    dedup: List[RealSentence] = []
    for s in out:
        key = s.text.casefold()
        if key in seen:
            continue
        seen.add(key)
        dedup.append(s)
    return dedup


def next_real_sentence(
    *,
    sources: Optional[Iterable[str]] = None,
    seed: Optional[int] = None,
    used_keys: Optional[Iterable[str]] = None,
) -> Optional[RealSentence]:
    """Return one randomly-chosen real sentence, or ``None`` if no source
    has anything that passes the filters.

    ``used_keys`` lets the caller skip sentences already proposed this
    session (pass the casefolded text of each accepted round).
    """
    pool = harvest_all(sources=sources)
    if not pool:
        return None
    skip = set(k.casefold() for k in (used_keys or []))
    pool = [s for s in pool if s.text.casefold() not in skip]
    if not pool:
        return None
    rng = random.Random(seed) if seed is not None else random.Random()
    return rng.choice(pool)


# ── CLI ──────────────────────────────────────────────────────────────────


def _cli() -> int:
    import argparse

    parser = argparse.ArgumentParser(
        description="Propose a real sentence for the Stigmergic Speech Game."
    )
    parser.add_argument(
        "--source",
        action="append",
        choices=("digest", "journal", "conversation", "manifest"),
        help="Restrict to one or more source kinds (repeatable).",
    )
    parser.add_argument(
        "--count",
        type=int,
        default=1,
        help="How many distinct sentences to propose (default 1).",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Deterministic rng seed (omit for non-deterministic).",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="List ALL passing sentences instead of sampling.",
    )
    args = parser.parse_args()

    pool = harvest_all(sources=args.source)
    if args.list:
        for s in pool:
            print(f"[{s.source_kind:12s}] {s.text}")
        print(f"\n# {len(pool)} sentences from {len(set(s.source_kind for s in pool))} sources")
        return 0
    used = set()
    for _ in range(max(1, args.count)):
        out = next_real_sentence(
            sources=args.source,
            seed=args.seed,
            used_keys=used,
        )
        if out is None:
            print("# no sentences passed the filters", flush=True)
            return 1
        print(f"[{out.source_kind}] {out.text}")
        print(f"  source_path: {out.source_path}  ({out.word_count} words)")
        used.add(out.text.casefold())
    return 0


if __name__ == "__main__":
    raise SystemExit(_cli())
