__all__ = ["_OLLAMA_URL", "_DEFAULT_WHISPER_MODEL", "_AUDIO_RATE", "_AUDIO_CHANS", "_MAX_RECORD_S", "_MAX_RESPONSE_CHARS", "_SOFT_CLIP_CEIL", "_PEAK_TARGET", "_PEAK_NORM_FLOOR", "_VAD_NOISE_HALFLIFE_S", "_HISTORY_TURNS", "_GROUNDED_HISTORY_TURNS", "_TTS_MAX_CHARS_DEFAULT"]
import os

_OLLAMA_URL = "http://127.0.0.1:11434"
_DEFAULT_WHISPER_MODEL = os.environ.get("SIFTA_WHISPER_MODEL", "tiny.en").strip() or "tiny.en"

# Audio Engine
_AUDIO_RATE = 16_000
_AUDIO_CHANS = 1
_MAX_RECORD_S = 60
_MAX_RESPONSE_CHARS = 1200
_SOFT_CLIP_CEIL = 0.98
_PEAK_TARGET = 0.90
_PEAK_NORM_FLOOR = 0.05
_VAD_NOISE_HALFLIFE_S = 4.0

# Memory Context Window
_HISTORY_TURNS = 8
_GROUNDED_HISTORY_TURNS = 3

# TTS constraints
_TTS_MAX_CHARS_DEFAULT = 320
