#!/usr/bin/env python3
"""
System/swarm_calendar_motor.py — Premotor Cortex
══════════════════════════════════════════════════════════════════════
SIFTA OS — DeepMind Cognitive Suite

The Calendar Motor. Allows Alice to project her physiological logic forward in 
time by dropping physical markers into the Architect's Reminders app.
"""

import json
import time
import subprocess
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

try:
    from System.jsonl_file_lock import append_line_locked
except ImportError:
    def append_line_locked(path, line, *, encoding="utf-8"):
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "a", encoding=encoding) as f:
            f.write(line)

class SwarmCalendarMotor:
    def __init__(self):
        self.state_dir = Path(".sifta_state")
        self.ledger = self.state_dir / "calendar_motor_traces.jsonl"
        self.ledger.parent.mkdir(parents=True, exist_ok=True)

    def write_reminder(self, task_name: str, notes: str = ""):
        """Schedules a new reminder in the default list."""
        try:
            safe_task = task_name.replace('"', '\\"')
            safe_notes = notes.replace('"', '\\"')
            
            script = f'''
            tell application "Reminders"
                make new reminder with properties {{name:"{safe_task}", body:"{safe_notes}"}}
            end tell
            '''
            
            subprocess.run(["osascript", "-e", script], check=True)
            
            trace = {
                "transaction_type": "PREMOTOR_PLANNING",
                "target": "Reminders",
                "task": task_name,
                "timestamp": time.time()
            }
            append_line_locked(self.ledger, json.dumps(trace) + "\n")
            return trace
        except Exception as e:
            return {"error": str(e)}

def _smoke():
    print("\n=== SIFTA CALENDAR MOTOR : SMOKE TEST ===")
    motor = SwarmCalendarMotor()
    print("[*] Projecting future state into Reminders...")
    # Intentionally tagging as a smoke test so the Architecture knows it's automated.
    res = motor.write_reminder("SIFTA Swarm OS Automated Boot Sync (Safe to delete)", notes="Generated by swarm_calendar_motor.py _smoke() test.")
    print(json.dumps(res, indent=2))
    print("[PASS] Premotor Cortex wired to Host Reminders.")

if __name__ == "__main__":
    _smoke()
