"""Public still-image capability: explicit intent and session-bound artifacts.

This service never teaches public prompts to owner memory or executes model tool text.
"""
from __future__ import annotations

import fcntl
import hashlib
import io
import json
import os
from pathlib import Path
import re
import secrets
import time
from urllib.parse import urlencode

from System import swarm_bonsai_image_organ as bonsai
from System.jsonl_file_lock import append_line_locked

STATE_DIR = Path(__file__).resolve().parent.parent / ".sifta_state"
MAX_IMAGE_BYTES = 16 * 1024 * 1024
_MEDIA = re.compile(
    r"^(?:please\s+|can\s+you\s+|could\s+you\s+|te\s+rog\s+|v[aă]\s+rog\s+|imi\s+po[tți]\s+)?/?"
    r"(?:create|generate|make|draw|paint|me\s+a\s+|cre[eă]az[aă]|genereaz[aă]|deseneaz[aă]|f[aă]\s+o\s+)\b"
    r"(?P<body>[\s\S]*)$", re.IGNORECASE,
)


# Conversational fillers visitors type before the actual request ("ok, create
# a photo of ..."). Stripped before intent matching so plain language works.
_LEAD_FILLER_RE = re.compile(
    r"^\s*(?:"
    r"ok(?:ay)?|hey|hi|hello|alice|salut|bun[aă]|bine"
    r"|can\s+you|could\s+you|will\s+you|would\s+you"
    r"|te\s+rog|v[aă]\s+rog|po[tți]|imi\s+po[tți]|hai"
    r")\b[\s,:;!?]*",
    re.I,
)


def _strip_lead_filler(text: str) -> str:
    """Drop small-talk prefixes so 'ok, create a photo of X' still dispatches."""
    prev = text = str(text or "").strip()
    for _ in range(4):  # bounded: 'ok te rog, create ...' chains
        stripped = _LEAD_FILLER_RE.sub("", prev, count=1)
        if stripped == prev:
            break
        prev = stripped
    return prev.strip()


def media_intent(text: str) -> str:
    text = _strip_lead_filler(text)
    match = _MEDIA.match(text)
    if not match:
        return ""
    body = match.group("body")
    # A poster is a still deliverable. Do this before subject words such as
    # "movie" or "film", and ignore quoted title text when deciding format.
    unquoted = re.sub(r"(['\"]).*?\1|[“”].*?[“”]", " ", body)
    poster = bool(re.search(r"\b(movie|film)\s+poster\b|\bposter\b|\baffiche\b", unquoted, re.I))
    moving_poster = bool(re.search(r"\b(animated|moving|video)\s+poster\b", unquoted, re.I))
    if poster and not moving_poster:
        return "image"
    explicit_motion = bool(re.search(r"\b(video|animation|animated|clip|anima[tț]ie)\b", unquoted, re.I))
    if explicit_motion:
        return "video"
    explicit_still = bool(
        text.lower().startswith("/create")
        # "desenează o pisică": the verb itself (draw/paint) is the still intent
        # even when the body names only the subject.
        or re.search(
            r"\b(photo|picture|image|painting|drawing|portrait|foto|fotografie|imagine|poz[aă]|desen)\b",
            body,
            re.I,
        )
        # "draw a cat": the matched VERB itself is still intent even when the
        # body names only the subject.
        or re.search(r"\b(draw|paint|deseneaz[aă])\b", _strip_lead_filler(text), re.I)
    )
    if explicit_still:
        return "image"
    # "movie" and "film" alone describe a moving medium; a quoted title or
    # a poster has already been handled above.
    if re.search(r"\b(movie|film)\b", unquoted, re.I):
        return "video"
    return ""


def public_capabilities() -> dict:
    ready = bool(bonsai.bonsai_backend_status().get("ok"))
    return {"text": True, "image_generation": ready, "image_command": "/create a photo of ...",
            "video_generation": False, "image_backend": "local still-image capability"}


def capability_prompt() -> str:
    available = public_capabilities()["image_generation"]
    return (
        "PUBLIC FEATURES: text conversation and visitor attachments. "
        "Photo requests use /create a photo of ... or Create a picture of ...; "
        + ("my local still-image capability is configured. " if available else
           "my local still-image capability is currently unavailable. ")
        + "Video generation is not available; offer a still image instead. "
        "A photo exists only after an image receipt, never because you describe one. "
        "Do not claim an image was generated by your text-model response."
    )


def _key(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _save(path: Path, row: dict) -> None:
    temporary = path.with_suffix(".tmp")
    temporary.write_text(json.dumps(row, sort_keys=True), encoding="utf-8")
    os.chmod(temporary, 0o600)
    temporary.replace(path)


def _public_result(row: dict, session_id: str) -> dict:
    images = []
    if row["status"] == "IMAGE_GENERATED":
        images = [{"name": "Alice-generated-image.png", "mime": "image/png", "kind": "generated_image",
                   "size_bytes": row["size_bytes"], "sha256": row["sha256"],
                   "url": "/api/generated-image?" + urlencode({"image_id": row["image_id"], "session_id": session_id})}]
    # Provider/model identity stays in the local manifest and diagnostics; the
    # visitor sees Alice's capability, not an internal organ brand.
    return {"reply": row["reply"], "model": "local_image_generator", "status": row["status"], "images": images}


def _recent_reply_variants(root: Path, session_hash: str) -> set[str]:
    """Read only recent same-session style choices, not prompt or owner data."""
    variants: list[tuple[float, str]] = []
    try:
        for manifest in root.glob("*.json"):
            row = json.loads(manifest.read_text(encoding="utf-8"))
            if row.get("session_hash") != session_hash:
                continue
            variant = str(row.get("reply_variant") or "")
            if variant:
                variants.append((float(row.get("ts") or 0.0), variant))
    except (OSError, TypeError, ValueError, json.JSONDecodeError):
        return set()
    variants.sort(reverse=True)
    return {variant for _, variant in variants[:8]}


def _contextual_image_reply(prompt: str, session_id: str, root: Path) -> tuple[str, str]:
    """Choose a varied, grounded response without pretending to see more than the prompt.

    Variation is bounded and receipt-backed: it changes the conversational
    framing, while the prompt and AI-generated label remain explicit. The same
    turn is still idempotent because its manifest is returned before this is
    called again.
    """
    lower = prompt.lower()
    if re.search(r"\b(bonsai|tree|forest|garden|nature|copac|pădure|natur[aă])\b", lower):
        family = "nature"
        templates = [
            "I translated your nature prompt into a still image: {prompt}",
            "I took your natural-world idea and rendered one still image: {prompt}",
            "I turned your requested nature scene into a local still image: {prompt}",
        ]
    elif re.search(r"\b(person|portrait|face|people|persoan[aă]|portret)\b", lower):
        family = "portrait"
        templates = [
            "I rendered the portrait request as a still image: {prompt}",
            "The local image organ translated your character prompt into a still: {prompt}",
            "I composed a still from your portrait idea: {prompt}",
        ]
    elif re.search(r"\b(peace|world|pace|lume|război|razboi)\b", lower):
        family = "world"
        templates = [
            "I turned your world-scale idea into a still image: {prompt}",
            "I rendered a visual interpretation of your request: {prompt}",
            "I made a still from that larger idea: {prompt}",
        ]
    else:
        family = "general"
        templates = [
            "I translated your prompt into a local still image: {prompt}",
            "I made a still interpretation of your request: {prompt}",
            "I rendered your idea locally: {prompt}",
        ]
    session_hash = _key(session_id)
    recent = _recent_reply_variants(root, session_hash)
    available = [(f"{family}_{index}", template) for index, template in enumerate(templates)]
    fresh = [item for item in available if item[0] not in recent]
    variant, template = secrets.choice(fresh or available)
    normalized = re.sub(r"\s+", " ", prompt).strip()[:240]
    return template.format(prompt=f"“{normalized}”"), variant


def handle_media_request(queued: dict, *, state_dir: Path = STATE_DIR) -> dict | None:
    prompt = str(queued.get("prompt_text") or queued.get("text") or "").strip()
    # /speak is a text-to-mouth command, not permission to generate from its quotation.
    if queued.get("speak_requested"):
        return None
    intent = media_intent(prompt)
    if not intent:
        return None
    sid, turn_id = str(queued.get("session_id") or ""), str(queued.get("turn_id") or "")
    if not sid or not turn_id:
        raise ValueError("session and turn required")
    root = Path(state_dir) / "web_generated_images"
    root.mkdir(parents=True, exist_ok=True, mode=0o700)
    image_id = _key(sid + "\0" + turn_id)
    manifest = root / (image_id + ".json")
    with (root / (image_id + ".lock")).open("a") as turn_lock:
        fcntl.flock(turn_lock, fcntl.LOCK_EX)
        if manifest.exists():
            return _public_result(json.loads(manifest.read_text()), sid)
        row = {"ts": time.time(), "turn_id": turn_id, "image_id": image_id,
               "session_hash": _key(sid), "prompt_sha256": _key(prompt), "model": bonsai.MODEL_ID,
               "truth_label": "OBSERVED_WEB_IMAGE_RESULT_V1", "owner_authority": False}
        if intent == "video":
            row.update(status="VIDEO_UNAVAILABLE", reply="I can offer still images, not video. Ask /create a photo of your scene.")
        elif not bonsai.bonsai_backend_status().get("ok"):
            row.update(status="IMAGE_BACKEND_UNAVAILABLE", reply="I can't generate that image yet. No image was generated because my local image capability is unavailable.")
        else:
            # One GPU image job across desktop/headless processes, without blocking chat queues.
            with (root / "generation.lock").open("a") as generation_lock:
                try:
                    fcntl.flock(generation_lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
                except BlockingIOError:
                    row.update(status="IMAGE_BUSY", reply="I'm processing another image right now. Please try again shortly.")
                else:
                    try:
                        result = bonsai.generate_bonsai_image(prompt.removeprefix("/create").strip())
                        if not result.get("ok"):
                            raise RuntimeError("backend_failed")
                        source = Path(result["image_path"])
                        if source.stat().st_size > MAX_IMAGE_BYTES:
                            raise ValueError("image_too_large")
                        data = source.read_bytes()
                        from PIL import Image
                        with Image.open(io.BytesIO(data)) as picture:
                            if picture.format != "PNG":
                                raise ValueError("expected_png")
                            picture.verify()
                        destination = root / (image_id + ".png")
                        destination.write_bytes(data)
                        os.chmod(destination, 0o600)
                        reply, variant = _contextual_image_reply(prompt, sid, root)
                        row.update(status="IMAGE_GENERATED", reply=reply + ". #SIFTA.",
                                   reply_variant=variant, sha256=hashlib.sha256(data).hexdigest(), size_bytes=len(data))
                    except Exception as exc:
                        row.update(status="IMAGE_FAILED", error_type=type(exc).__name__,
                                   reply="I couldn't finish that image. No image was generated. You can ask me to try again.")
        _save(manifest, row)
        append_line_locked(Path(state_dir) / "web_image_receipts.jsonl", json.dumps(row) + "\n")
        return _public_result(row, sid)


def read_session_image(image_id: str, session_id: str, *, state_dir: Path = STATE_DIR) -> bytes | None:
    if not session_id or not re.fullmatch(r"[0-9a-f]{64}", image_id):
        return None
    root = Path(state_dir) / "web_generated_images"
    manifest, image = root / (image_id + ".json"), root / (image_id + ".png")
    try:
        if manifest.is_symlink() or image.is_symlink():
            return None
        row = json.loads(manifest.read_text())
        if row.get("session_hash") != _key(session_id) or row.get("status") != "IMAGE_GENERATED":
            return None
        if image.stat().st_size > MAX_IMAGE_BYTES:
            return None
        data = image.read_bytes()
        if hashlib.sha256(data).hexdigest() != row.get("sha256"):
            return None
        return data
    except (OSError, ValueError, KeyError):
        return None
