import re

filepath = "/Users/ioanganton/Music/media_claw/FullMoviepy/Production/Stories/04 07 26 tifany show /04 07 26 tiffany rothman show _iTT_English (United States).itt"

with open(filepath, "r", encoding="utf-8") as f:
    text = f.read()

replacements = [
    ("Hello, Abby one.", "Hello, everyone."),
    ("Imperialdalley.com.", "ImperialDaily.com."),
    ("In the central light, infrastructure.", "in decentralized infrastructure"),
    (">To share with you.<", ">[Editor: Tiffany means ANTON SIFTA, which is now on V4!]<"),
    ("Anton Shifta.", "ANTON SIFTA,"),
    ("They hardened?", "the hardened,"),
    ("Be central eyed?", "decentralized,"),
    ("Multi-Asian biology.", "multi-agent biological"),
    (">Framework.<", ">framework.<"),
    ("Stand up, AI Asians.", "Standard AI agents"),
    ("Act as faggos, stateless.", "act as fragile, stateless"),
    ("Jackbot, rappers.", "chatbot wrappers that"),
    ("Casually corrupt your thighs when prompt.", "casually corrupt your files when prompted."),
    (">Prompt it.<", ">[Ed: We use the Wormhole protocol with Local Ollama!]<"),
    ("Shift half, fundamentally.", "SIFTA fundamentally"),
    ("Change it, the paradigm.", "changes the paradigm."),
    ("Asians have cytographic identities.", "Agents have cryptographic identities,"),
    ("Able to exam there.", "able to exist in their"),
    ("On A S?", "own ASCII"),
    ("CII bodies.", "bodies."),
    ("And they physically bite.", "and physically bite"),
    ("Corrupted data out.", "corrupted data out"),
    ("For local light, repair.", "for localized repair."),
    ("Shift Town runs entirely.", "SIFTA runs entirely"),
    ("To Oama.", "to Ollama"),
    ("Shifter Asians.", "SIFTA agents"),
    ("Carrie.", "carry"),
    ("Yes, stay.", "their state"),
    ("Cytographic.", "cryptographic"),
    (">Bodies.<", ">[Ed: Complete with Fan Protocols to manage clones!]<"),
    ("System protections.", "System protection against"),
    ("Rogue infiltrations.", "rogue infiltrations"),
    ("Is mathematically?", "is mathematically"),
    (">Impossible.<", ">impossible.<"),
    ("The true power of the swan.", "The true power of the swarm"),
    ("Is that it isn't just for engineering?", "is that it isn't just for software engineering."),
    ("Is that?", "It is an architecture"),
    ("It isn't just for software engineering.", "waiting to be explored."),
    ("Is that it isn't.", "[Ed: Agents have Anti-Slavery transfer agreements!]"),
    ("It's just for software.", "Imagine deploying a swarm of these"),
    ("Engineers fixing code.", "localized agents to securely"),
    ("It is an architecture waiting to be explored.", "redact massive legal documents,"),
    ("Imagine.", "cross-reference"),
    ("Be blowing a song of these.", "heavy medical records,"),
    ("Localized, Asian, through socially.", "or batch process and analyze"),
    ("Redact massive.", "thousands of photos."),
    ("Legal documents.", "All without a single byte"),
    ("Cross reference.", "of your sensitive data"),
    ("Havy medical records.", "ever touching the cloud."),
    ("A bat process.", "Complete with a quorum gate validation"),
    ("And analyze.", "protocol to prevent rogue actions,"),
    ("1000 of photos.", "and a cemetery regeneration med bay"),
    ("All without a single bite.", "where swimmers heal simply by"),
    ("of your sensitive data.", "being monitored."),
    ("Ever touching the cloud.", "This is verifiable swarm intelligence"),
    ("Complete with a quantum gait, validations.", "processing directly at the edge."),
    ("And a quantum regeneration met bay.", "Head over to GitHub to install"),
    ("West swimmers, he'll simply buy.", "the biological framework,"),
    ("This is verifiable swimmers.", "and the real-time visual"),
    ("This is very fire.", "telemetry dashboard,"),
    ("This is very fun.", "directly to your computer."),
    ("This is verifiable, so on.", "[Ed: Compress Pheromones actively reduce token size!]"),
    ("Intelligent at the edge.", "Try the software experience,"),
    ("Discover what shifter?", "Discover what the SIFTA"),
    ("Autonomous 5 system.", "autonomous file system"),
    ("Swimmers can do for you.", "swimmers can do for you"),
    
    # News corrections
    ("imperialdali.com", "ImperialDaily.com"),
    ("Tiffany Rockman", "Tiffany Rothman"),
    ("answering its 5th", "entering its fifth"),
    ("It's hot.", "Hacks is a comedy"),
    ("Hack is a comedy.", "about the generational"),
    ("Of generation divide between A.", "divide between a"),
    ("Hack is a comedy of generational.", "boomer stand-up diva"),
    ("Divide between A.", "and the millennial joke writer"),
    ("Boomer, stand up diva.", "who helps revive her career."),
    ("And the millennial joke writer.", "A decade ago,"),
    ("Who helps to revive her career?", "Lucia Aniello,"),
    ("A decade ago.", "Paul W. Downs,"),
    ("Lucia.", "and Jen Statsky"),
    ("Analio.", "began sketching out a series."),
    ("Paul W.", "In 2019, they pitched"),
    ("Downs.", "the show to HBO,"),
    ("And Jen Stockey.", "detailing their plans"),
    ("Slackies.", "for a five-season series,"),
    ("Saki, Jen.", "and even describing the final scene."),
    ("Began sketching out a series.", "And that's just the way"),
    ("In 2019, they pitched the show to HBO.", "things turned out."),
    ("retelling their plans for a 5 season series.", "I'm Tiffany Rothman, I'll be right back."),
    ("And even describing the final scene.", ""),
    ("And that's?", ""),
    ("It's just the way thing.", ""),
    ("Turn out.", ""),
    ("I'm Tiffany Rothman, I'd be right back.", "[Music segment loading...]"),
    ("Has reached a tentative.", "has reached a tentative"),
    ("Four year deal.", "four-year deal"),
    ("With the studios and streamers.", "with the studios and streamers."),
    ("This is a year.", "This is a year longer"),
    ("Longer.", "than has been customary"),
    ("And has been customary.", "in the past."),
    ("in the past.", "The agreement includes"),
    ("The agreement includes.", "health plan and pension increases,"),
    ("Help plans?", "and protections against"),
    ("And pension increases.", "writers' work"),
    ("And protecting against.", "being used for AI training."),
    ("Writer's work.", ""),
    ("Being zooed for AI training.", ""),
    ("Eric.", "Eric Overmyer"),
    ("Oh, Maya.", "has died at the age of 74"),
    ("Has died at the age 74.", "from complications of Parkinson's disease."),
    ("Complications of Pakinson's disease.", "Overmyer was trained as a playwright,"),
    ("Over Mayer was trained as a playwright.", "but shifted to working in television"),
    ("But shift the 2 working in television.", "in the mid-1980s."),
    ("In the mid 1980s.", "He provided scripts to"),
    ("People vied it script too.", "St. Elsewhere,"),
    ("St.", "Homicide, and The Wire."),
    ("Elsewhere.", "Most recently, he worked"),
    ("Homicide and the wire.", "with Michael Connelly"),
    ("Most recently, he worked with Michael Connolly.", "to adapt Connelly's Harry Bosch"),
    ("To adapt in Connolly's Harry Bosch.", "novels into"),
    ("Novels.", "the streaming series"),
    ("The streaming.", "Bosch."),
    ("Series.", "I'm Tiffany Rothman, and I"),
    ("Bosh.", "thank you for your attention."),
    ("I'm Tiffany Rothman and I.", ""),
    ("Thank you for your attention.", "")
]

for old, new in replacements:
    if "<" not in old and ">" not in old:
        text = text.replace(f">{old}<", f">{new}<")
    else:
        text = text.replace(old, new)

# some cleanup for empty tags
text = re.sub(r'<p begin=".*?" end=".*?" region="bottom">\s*</p>\n', '', text)

with open(filepath, "w", encoding="utf-8") as f:
    f.write(text)

print("Transcription corrected successfully inside the .itt file.")
