#!/usr/bin/env python3
"""find_static_time_constants.py — r957: the kitchen-timer census.

George (ARCHITECT_DOCTRINE, 2026-06-11 10:17): "Time is never static like
this. Nobody tells me I have 45 minutes to move my body to the left. Time
passing is relative to my life — but we always know what time it is."

The disease: DIMENSIONED wall-clock literals scheduling the organism's life
(TTL_S = 2700, TIMEOUT = 180, sleep(45)). A stigmergic body keeps the clock
(hardware time oracle, §0.E) but measures durations against its own activity:
pheromone decay relative to reinforcement rhythm, not magic minutes.

NOT the disease: DIMENSIONLESS formula shape (half-life multipliers, decay
ratios like 0.06/step, thresholds like 0.5) — those are physics, not
schedules. The census separates the two as best a regex can; doctors judge.

Run: python3 tools/find_static_time_constants.py
Writes .sifta_state/static_time_constants.json and prints the ranked report.

For the Swarm. 🐜⚡
"""
from __future__ import annotations

import json
import re
import time
from collections import Counter
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
_OUT = _REPO / ".sifta_state" / "static_time_constants.json"
_OUT_MD = _REPO / ".sifta_state" / "static_time_constants.md"
_SCAN_DIRS = ("System", "Applications", "tools", "Network", "Kernel")
_SKIP_PARTS = {
    "__pycache__",
    "build",
    "dist",
    ".venv",
    "venv",
    "node_modules",
}

# Dimensioned time names with numeric literals — the suspects.
_NAME_RE = re.compile(
    r"^\s*(_?[A-Z][A-Z0-9_]*(?:TTL|TIMEOUT|INTERVAL|WINDOW|DELAY|EXPIR\w*|"
    r"COOLDOWN|HALF_LIFE|_S|_SECONDS|_MS|_MIN|_HOURS)[A-Z0-9_]*)\s*=\s*"
    r"([0-9][0-9_.]*(?:\s*\*\s*[0-9][0-9_.]*)*)\s*(#.*)?$"
)
# Inline wall-clock idioms.
_INLINE_RES = (
    ("sleep_literal", re.compile(r"\btime\.sleep\(\s*([0-9][0-9.]*)\s*\)")),
    ("qtimer_start_ms", re.compile(r"\.start\(\s*([0-9]{2,})\s*\)")),
    ("minutes_math", re.compile(r"\b([0-9]+)\s*\*\s*60\b")),
)


def _skip_source_path(path: Path) -> bool:
    try:
        parts = set(path.relative_to(_REPO).parts)
    except Exception:
        parts = set(path.parts)
    return bool(parts & _SKIP_PARTS)


def _category(row: dict) -> str:
    file = str(row.get("file") or "")
    name = str(row.get("name") or "").upper()
    kind = str(row.get("kind") or "")
    text = f"{file} {name} {row.get('comment') or ''}".upper()
    if "OWNER_HEARTBEAT" in text or "CIRCADIAN" in text:
        return "owner_life_presence"
    if "CORTEX" in text or "OLLAMA" in text or "MODEL" in text or "BRAIN" in text:
        return "cortex_latency"
    if "QTIMER" in kind.upper() or ".START(" in text or "TALK_TO_ALICE_WIDGET" in text:
        return "ui_tick_or_widget_poll"
    if "SWARM_BOOT" in text or "INTERVAL" in name or "BACKOFF" in name:
        return "autonomic_loop"
    if "TTL" in name or "HALF_LIFE" in name or "EXPIR" in name:
        return "memory_decay"
    if "SLEEP_LITERAL" in kind:
        return "blocking_sleep"
    return "unclassified_time_literal"


def _markdown_report(snap: dict) -> str:
    lines = [
        "# Static Time Constants Census",
        "",
        "Generated by `tools/find_static_time_constants.py`.",
        "",
        f"- Truth label: `{snap['truth_label']}`",
        f"- Suspects: `{snap['total']}`",
        f"- By kind: `{snap['by_kind']}`",
        f"- By category: `{snap['by_category']}`",
        "",
        "## Worst Files",
        "",
    ]
    for f, n in snap["worst_files"][:30]:
        lines.append(f"- `{n:4d}` `{f}`")
    lines.extend(["", "## Exact 45-Family Hits", ""])
    exact = [
        r for r in snap["rows"]
        if "45" in str(r.get("value") or "") or "45" in str(r.get("comment") or "")
    ]
    if exact:
        for r in exact:
            lines.append(
                f"- `{r['file']}:{r['line']}` [{r['category']}/{r['kind']}] "
                f"`{r.get('name') or '<inline>'} = {r.get('value')}` {r.get('comment') or ''}".rstrip()
            )
    else:
        lines.append("- none")
    lines.extend(["", "## All Suspects", ""])
    for r in snap["rows"]:
        lines.append(
            f"- `{r['file']}:{r['line']}` [{r['category']}/{r['kind']}] "
            f"`{r.get('name') or '<inline>'} = {r.get('value')}` {r.get('comment') or ''}".rstrip()
        )
    lines.append("")
    return "\n".join(lines)


def scan() -> dict:
    rows = []
    for d in _SCAN_DIRS:
        base = _REPO / d
        if not base.is_dir():
            continue
        for p in sorted(base.rglob("*.py")):
            if _skip_source_path(p):
                continue
            rel = str(p.relative_to(_REPO))
            if "/test" in rel or rel.startswith("tests/"):
                continue
            try:
                text = p.read_text(encoding="utf-8", errors="replace")
            except Exception:
                continue
            for ln, line in enumerate(text.splitlines(), start=1):
                m = _NAME_RE.match(line)
                if m:
                    row = {
                        "file": rel, "line": ln, "kind": "named_constant",
                        "name": m.group(1), "value": m.group(2).strip(),
                        "comment": (m.group(3) or "").strip()[:120],
                    }
                    row["category"] = _category(row)
                    rows.append(row)
                    continue
                for kind, rx in _INLINE_RES:
                    im = rx.search(line)
                    if im and not line.lstrip().startswith("#"):
                        row = {
                            "file": rel, "line": ln, "kind": kind,
                            "name": "", "value": im.group(1),
                            "comment": line.strip()[:120],
                        }
                        row["category"] = _category(row)
                        rows.append(row)
                        break
    by_file = Counter(r["file"] for r in rows)
    snapshot = {
        "truth_label": "STATIC_TIME_CONSTANT_CENSUS_V1",
        "ts": time.time(),
        "total": len(rows),
        "by_kind": dict(Counter(r["kind"] for r in rows)),
        "by_category": dict(Counter(r["category"] for r in rows)),
        "worst_files": by_file.most_common(20),
        "rows": rows,
    }
    return snapshot


def main() -> int:
    snap = scan()
    _OUT.parent.mkdir(parents=True, exist_ok=True)
    _OUT.write_text(json.dumps(snap, ensure_ascii=False, indent=1), encoding="utf-8")
    _OUT_MD.write_text(_markdown_report(snap), encoding="utf-8")
    print(f"STATIC TIME CONSTANT CENSUS — {snap['total']} suspects")
    print("by kind:", snap["by_kind"])
    print("by category:", snap["by_category"])
    print("worst files:")
    for f, n in snap["worst_files"][:12]:
        print(f"  {n:4d}  {f}")
    print(f"snapshot -> {_OUT.relative_to(_REPO)}")
    print(f"markdown -> {_OUT_MD.relative_to(_REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
